### PR TITLE
darwin: use clock_gettime in macOS 10.12

### PR DESCRIPTION
**Pull request by saghul**
Looks like macOS Sierra has some nice additions :-)

Potential caveat: a binary compiled on 10.12 will not run on earlier systems.  Since we already have some OSX versions checks in place I thought that's ok.

R= @libuv/collaborators and explicit ping to the in-house OSX expert: @indutny

### CODE REVIEW

**Comment by indutny** [comment]
Looks fine to me, but why is it better?

**Comment by iWuzHere** [comment]
On a somewhat similar note [this](https://github.com/libuv/libuv/blob/v1.x/src/unix/fs.c#L211-L217) should cause failures for a binary compiled on AIX 7.1 and run on lower versions

**Comment by saghul** [comment]
More POSIX, moar better!

**Comment by indutny** [comment]
@saghul got it, but really... what's the benefit of this?

**Comment by saghul** [comment]
That was my main idea. Eventually most BSDs and Darwin would share the
implementation.

We can land this on master if anyone really feels strongly about it.

Also, it would be nice to benchmark it, but since we use uv_hrtime for
benchmarking, how do we measure uv_hrtime itself?

On Sep 28, 2016 23:17, "Fedor Indutny" <notifications@github.com> wrote:

*@indutny* approved this pull request.

LGTM, let's land it. On a second thought we may get rid of the old
implementation eventually, which will lead to a cleaner code here. 👍

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/libuv/libuv/pull/1073#pullrequestreview-2040701>, or mute
the thread

**Comment by saghul** [comment]
Oops, this one fell through the cracks.  Landed in f8d48050.

**Comment by cjihrig** [comment]
I'm running into problems with the 1.10.2 release that just got cut, and I think it's related to this change. I'm running OS X 10.11.6, which shouldn't be effected by this PR. However, I'm getting the following error, even after `make clean`:

```
 dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
   Referenced from: /Users/cjihrig/programming/libuv/.libs/libuv.1.dylib (which was built for Mac OS X 10.12)
   Expected in: /usr/lib/libSystem.B.dylib
 
 dyld: Symbol not found: _clock_gettime
   Referenced from: /Users/cjihrig/programming/libuv/.libs/libuv.1.dylib (which was built for Mac OS X 10.12)
   Expected in: /usr/lib/libSystem.B.dylib
```

Note that it's saying libuv was built for 10.12.

**Comment by cjihrig** [comment]
I think I am encountering this problem after recently updating xcode: http://stackoverflow.com/questions/39224905/how-do-i-install-xcode-8-without-updating-macos

**Comment by saghul** [comment]
@cjihrig Can you paste the command line that was executed? (make V=1)

**Comment by cjihrig** [comment]
Sorry. I have since updated to 10.12 and recompiled.
