### ISSUE TITLE
libuv fails to be built with android-ndk-r12b after merging 7b9e25a9

### ISSUE THREAD

**Issue by ngkaho1234** [libuv/libuv#1029]
Output of android-configure:
['-Dtarget_arch=arm64', '-DOS=android', '-f', 'make-android', '/home/ngkaho1234/Workspace/volmgr/libuv/uv.gyp', '-I', '/home/ngkaho1234/Workspace/volmgr/libuv/common.gypi', '--depth=.', '-Goutput_dir=/home/ngkaho1234/Workspace/volmgr/libuv/out', '--generator-output', '/home/ngkaho1234/Workspace/volmgr/libuv/out', '-Dhost_arch=x64', '-Duv_library=static_library']

Output of make -C out:
test-tty.c:(.text.run_test_tty_pty+0x40): undefined reference to `openpty'

**Comment by saghul** [comment]
@ngkaho1234 can you try https://github.com/libuv/libuv/pull/1030 ?
