### ISSUE TITLE
Release proposal: v1.42.0

### ISSUE THREAD

**Issue by vtjnash** [libuv/libuv#3202]
I think it is time to release v1.42.0. Please leave any questions, comments, and concerns.

Notable changes:
https://github.com/libuv/libuv/compare/v1.41.0...v1.x

- win,tcp: make uv_close work more like unix
- cleanup,win: Remove _WIN32 guards on threadpool
- more errno mappings and fixes
- higher performance try-writes
- fix string encoding issue of uv_os_gethostname (note: MINGW-W64 upstream is broken on i686 due to https://sourceforge.net/p/mingw-w64/bugs/899/)
- zOS support
- Workarounds for a copy_file_range kernel bug
- Better support for TSan
- darwin: use RLIMIT_STACK for fsevents pthread

CI: https://ci.nodejs.org/job/libuv-test-commit/2169/

**Comment by richardlau** [comment]
> * zOS support

To clarify: libuv already had z/OS support before but it was significantly reworked under https://github.com/libuv/libuv/pull/3060.

**Comment by vtjnash** [comment]
Node CI: ~https://ci.nodejs.org/view/libuv/job/libuv-in-node/183/~ https://ci.nodejs.org/view/libuv/job/libuv-in-node/184/
libuv CI: https://ci.nodejs.org/job/libuv-test-commit/2171/

**Comment by vtjnash** [comment]
Did someone disable or misconfigure IPv6 on the AIX CI bots? They are now failing with ~https://github.com/libuv/libuv/issues/3134~:

```
not ok 141 - ip6_addr_link_local
# exit code 393222
# Output from process `ip6_addr_link_local`:
# Assertion failed in test/test-ip6-addr.c on line 75: 0 == uv_if_indextoname(iface_index, scoped_addr, &scoped_addr_len)
```

**Comment by richardlau** [comment]
@vtjnash That'd be https://github.com/nodejs/node/issues/39143. The machines were rebooted for some reason and the provisioning script autoconfigures IPv6 -- apparently before the interfaces that had IPv6 link local addresses were manually disabled but they come back on reboots. I've removed the interfaces again so we were back to how we were previous configured but I suspect there's a disconnect between assumptions made by libuv/Node.js tests about IPv6 link local addresses being scoped because they do not appear to be scoped on those interfaces that were being enabled.

**Comment by richardlau** [comment]
Ah okay there was another interface which I've also now disabled. CI is passing on AIX:
- https://ci.nodejs.org/job/libuv-test-commit-aix/2159/
- https://ci.nodejs.org/job/libuv-test-commit-aix-cmake/350/

**Comment by vtjnash** [comment]
Progress update: it appears that the premise of 80f2f826bf90b84e659321c0b7fd8af419acb85e  / 636a13b8c46c52413e1da1795a952bfc738f3c55 / 41468050745bc135247f587eae1c38e958fd8377 / b329d51ef4ce32f34c21a016a7c311ddeb077878 was fatally flawed, which now shows up as a hanging event loop (as the intended purpose of that commit was precisely to prevent libuv from updating the active bit correctly in this exact case). As far as I can tell, the problem described in that commit message does not seem to have ever existed, and instead it introduced an occasional deadlock. I am hoping that any underlying bugs that those patches were intended to work-around have since been fixed, so I am testing out reverting those.

The particular sequence of events causing the nodejs tests to fail is:
```
1. --> uv_shutdown(stream) # creates an active req, this prevents the termination of the loop
2. <-- uv__read_eof(stream) # notices that there is a shutdown in progress, leaves handle active also preventing termination of the loop
3. <-- uv__drain(stream) # closes active req, but leaves handle active (since active is not a function of reqs/writes/shutdown)
stream->shutdown_cb(stream) # cleanup notification gets called, and is the last event we will ever see on stream
# loop should have now been free to exit (no active reqs or handles) and to start calling uv_close on any remaining handle, but read_eof "forgot" to unref the handle, therefore, it is now impossible to get libuv to exit
```

Before the optimizations in this release for uv_try_write, we were getting instead the sequence, which bypasses the bug introduced in 80f2f826bf90b84e659321c0b7fd8af419acb85e by taking instead the expected "normal" path through the event loop:
```
1. --> uv_shutdown(stream)
2. <-- uv__drain(stream)
3. <-- uv__read_eof(stream)
```



N.B. There is a secondary failure here (that makes the above issue a visible problem) which is a resource leak bug in nodejs. These TLS handles are failing to close or garbage collect their underlying sockets in their shutdown callback. There won't be any more write events at that point, and we've already called EOF, so there won't be any more read events. But the nodejs runtime would apparently have preserved these dead handles forever (in the test suite, it appears they are getting cleaned up by process exit, hiding the issue normally, aside from the libuv bug). AFAICT, that resource leak is currently as-intended and by-design in nodejs, but that is out-of-scope for this issue right now.

**Comment by vtjnash** [comment]
https://github.com/libuv/libuv/pull/3233 seems to be the only remaining bug, so if that could get priority review, I should be able to finish this release soon.

Separately, but relatedly, the v1.41.1 security release is now published: https://dist.libuv.org/dist/v1.41.1/

**Comment by atsampson** [comment]
It would probably be a good idea to update the list of GPG keys for releases in MAINTAINERS.md, and make sure they're available from keyservers - the key used for the 1.41.1 release isn't listed there, for example (it's pubkey-vtjnash in the repository).

**Comment by vtjnash** [comment]
Got many more good commits in here now, so planning to make this release later tonight.

**Comment by vtjnash** [comment]
Mostly more doc and build improvements, and other minor fixes, plus a few more significant issues fixed:

- fix a bug that would cause libuv to hang if the user called uv_shutdown (causing CI issues in nodejs)
- darwin: fix uv_barrier race condition (under non-ideal usage)
- idna: fix OOB read in punycode decoder (security bug, also fixed in 1.41.1)
