### ISSUE TITLE
fatal error: pthread-barrier.h: No such file or directory

### ISSUE THREAD

**Issue by neevek** [libuv/libuv#891]
I am trying to build with libuv on Debian(2.6.32-042stab113.11, gcc 4.9.2),  failed with:

    In file included from /usr/include/uv.h:62:0,
                 from test.c:2:
    /usr/include/uv-unix.h:61:30: fatal error: pthread-barrier.h: No such file or directory
    # include "pthread-barrier.h"

I found that the file `pthread-barrier.h` was in `libuv/include` but was not installed in system include directory, so I copied it to `/usr/include`, now more errors occur:

    /usr/include/pthread-barrier.h:54:13: error: 'UV_BARRIER_STRUCT_PADDING' undeclared here (not in a function)
    char _pad[UV_BARRIER_STRUCT_PADDING];
             ^
    In file included from /usr/include/uv.h:62:0,
                 from test.c:2:
    /usr/include/uv-unix.h:136:9: error: unknown type name 'pthread_rwlock_t'
     typedef pthread_rwlock_t uv_rwlock_t;

P.S. All my code compiles & runs good on OSX.

**Comment by saghul** [comment]
That's weird. That file is only needed for Android and OSX, where we use our pthread_barrier_t fallback implementation. How did you compile and install libuv on your system?

**Comment by neevek** [comment]
This is how I built libuv on debian:

    git clone --depth=1 https://github.com/libuv/libuv.git
    cd libuv
    sh autogen.sh
    ./configure --prefix=/usr
    make && make install

Also I built my code with the following CFLAGS, but I don't think that would affect libuv:

    -c -Wall -O0 -g -std=c99

**Comment by saghul** [comment]
Does `make check` work for you?

**Comment by kthelgason** [comment]
The conditional include is based on whether `PTHREAD_BARRIER_SERIAL_THREAD` is defined. Do you have libc6 installed? Can you post the output of `./configure`?

**Comment by kthelgason** [comment]
Also, does building your code with `-pthread` solve the problem? I suspect it will.

**Comment by neevek** [comment]
@saghul `make check` passed in spite of some warnings.
@kthelgason , adding `-lpthread` did not help.

Output of `./configure --prefix=/usr`:

    ichecking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking for style of include used by make... GNU
    checking dependency style of gcc... gcc3
    checking if gcc supports -fvisibility=hidden flag... yes
    checking if gcc supports -g flag... yes
    checking if gcc supports -std=gnu89 flag... yes
    checking if gcc supports -pedantic flag... yes
    checking if gcc supports -Wall flag... yes
    checking if gcc supports -Wextra flag... yes
    checking if gcc supports -Wno-unused-parameter flag... yes
    checking for ar... ar
    checking the archiver (ar) interface... ar
    checking how to print strings... printf
    checking for a sed that does not truncate output... /bin/sed
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for fgrep... /bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1966080
    checking whether the shell understands some XSI constructs... yes
    checking whether the shell understands "+="... yes
    checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for mt... mt
    checking if mt is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... yes
    checking whether make supports nested variables... (cached) yes
    checking for dlopen in -ldl... yes
    checking for kstat_lookup in -lkstat... no
    checking for kvm_open in -lkvm... no
    checking for gethostbyname in -lnsl... yes
    checking for perfstat_cpu in -lperfstat... no
    checking for pthread_mutex_init in -lpthread... yes
    checking for clock_gettime in -lrt... yes
    checking for sendfile in -lsendfile... no
    checking for socket in -lsocket... no
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... no
    checking sys/ahafs_evProds.h usability... no
    checking sys/ahafs_evProds.h presence... no
    checking for sys/ahafs_evProds.h... no
    checking for pkg-config... no
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: executing depfiles commands
    config.status: executing libtool commands

Output of `make install`:

    make[1]: Entering directory '/home/neevek/libuv'
     /bin/mkdir -p '/usr/lib'
     /bin/bash ./libtool   --mode=install /usr/bin/install -c   libuv.la '/usr/lib'
    libtool: install: /usr/bin/install -c .libs/libuv.so.1.0.0 /usr/lib/libuv.so.1.0.0
    libtool: install: (cd /usr/lib && { ln -s -f libuv.so.1.0.0 libuv.so.1 || { rm -f libuv.so.1 && ln -s libuv.so.1.0.0 libuv.so.1; }; })
    libtool: install: (cd /usr/lib && { ln -s -f libuv.so.1.0.0 libuv.so || { rm -f libuv.so && ln -s libuv.so.1.0.0 libuv.so; }; })
    libtool: install: /usr/bin/install -c .libs/libuv.lai /usr/lib/libuv.la
    libtool: install: /usr/bin/install -c .libs/libuv.a /usr/lib/libuv.a
    libtool: install: chmod 644 /usr/lib/libuv.a


    libtool: install: ranlib /usr/lib/libuv.a
    libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin" ldconfig -n /usr/lib
    ----------------------------------------------------------------------


    Libraries have been installed in:
       /usr/lib

    If you ever happen to want to link against installed libraries
    in a given directory, LIBDIR, you must either use libtool, and
    specify the full pathname of the library, or use the `-LLIBDIR'
    flag during linking and do at least one of the following:
       - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
         during execution
       - add LIBDIR to the `LD_RUN_PATH' environment variable
         during linking
       - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
       - have your system administrator add LIBDIR to `/etc/ld.so.conf'

    See any operating system documentation about shared libraries for
    more information, such as the ld(1) and ld.so(8) manual pages.
    ----------------------------------------------------------------------
     /bin/mkdir -p '/usr/include'
     /usr/bin/install -c -m 644 include/uv.h include/uv-errno.h include/uv-threadpool.h include/uv-version.h include/uv-unix.h include/uv-linux.h '/usr/include'
    make[1]: Leaving directory '/home/neevek/libuv'

**Comment by saghul** [comment]
I cannot reproduce this. I installed libuv on my Debian Sid system to /usr/local, then made a simple test program which just called `uv_run` and compiled it as follows:

~~~~
cc t.c $(pkg-config --cflags libuv) $(pkg-config --libs libuv)
~~~~

**Comment by neevek** [comment]
OK, I found the culprit, it is the `c99` option that causes the error, after changing it to `gnu99`, the code compiles now.
But it is weird, why can `c99` get `PTHREAD_BARRIER_SERIAL_THREAD ` defined?

**Comment by bnoordhuis** [comment]
We can probably fix that by adding `-D_POSIX_C_SOURCE=200112` to the cpp flags.  The gyp build already does that.

@neevek Try adding that to your local build flags.

**Comment by bnoordhuis** [comment]
I had a look and I don't think we actually need to change anything.  We already set `-D_GNU_SOURCE` (which subsumes `-D_POSIX_C_SOURCE=200112`) but overriding CFLAGS through the environment of course removes that.

I'll close, not a libuv issue.  @neevek Just add either define to you local flags and you should be good to go.
