### ISSUE TITLE
src/win/udp.c: Incompatible with Visual C++ 9/C89

### ISSUE THREAD

**Issue by jamadden** [libuv/libuv#2861]
* **Version**: 1.38.0 (upgrading from 1.36)
* **Platform**: Windows (AppVeyor VM)

gevent supports Python 2.7, which has a particular compiler it must use (Visual C++ 9). When updating from 1.36 to 1.38, I find that I can no longer compile with that compiler. [Error message](https://ci.appveyor.com/project/denik/gevent/builds/33014124/job/lug3fye0ko2gbe7q#L800):

```
   C:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DLIBUV_EMBED=1 -D_GNU_SOURCE=1 -DWIN32=1 -D_CRT_SECURE_NO_DEPRECATE=1 -D_CRT_NONSTDC_NO_DEPRECATE=1 -D_CRT_SECURE_NO_WARNINGS=1 -D_WIN32_WINNT=0x0600 -DWIN32_LEAN_AND_MEAN=1 -IC:\projects\gevent\deps\libuv\include -IC:\projects\gevent\deps\libuv\src -IC:\projects\gevent\src\gevent -IC:\Python27-x64\include -IC:\Python27-x64\PC /Tcdeps\libuv\src\win/udp.c /Fobuild\temp.win-amd64-2.7\Release\deps\libuv\src\win/udp.obj    udp.c
    deps\libuv\src\win/udp.c(777) : error C2143: syntax error : missing ';' before 'type'
    deps\libuv\src\win/udp.c(778) : error C2143: syntax error : missing ';' before 'type'
    error: command 'C:\\Users\\appveyor\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
```

It appears the `STATIC_ASSERT` macros on those lines are incompatible with the C89 syntax required by this compiler. I'm not sure what the problem was, other `STATIC_ASSERT` statements (pipe.c, fs.c) compiled successfully; I guess it's that there's code that comes before these uses, and these uses expand to something that looks like a variable definition.

My temporary patch was just to comment them out, though of course that's not ideal:
```patch
diff --git a/deps/libuv/src/win/udp.c b/deps/libuv/src/win/udp.c
index 1c4977af..958dee28 100644
--- a/deps/libuv/src/win/udp.c
+++ b/deps/libuv/src/win/udp.c
@@ -774,8 +774,8 @@ int uv__udp_set_source_membership6(uv_udp_t* handle,
     mreq.gsr_interface = 0;
   }

-  STATIC_ASSERT(sizeof(mreq.gsr_group) >= sizeof(*multicast_addr));
-  STATIC_ASSERT(sizeof(mreq.gsr_source) >= sizeof(*source_addr));
+//  STATIC_ASSERT(sizeof(mreq.gsr_group) >= sizeof(*multicast_addr));
+//  STATIC_ASSERT(sizeof(mreq.gsr_source) >= sizeof(*source_addr));
```

**Comment by bnoordhuis** [comment]
I can fix that, however... we're in the process of phasing out pre-VS2015 support, see #2821 (and that's really just making _de jure_ what was already _de facto_ the case.)

With python 2 EOL there's no reason for us to support VS 2008 any longer. If you still want to support it, you'll be on the hook for maintaining patches as we are unlikely to accept them.

**Comment by jamadden** [comment]
> I can fix that

Thank you!

> With python 2 EOL there's no reason for us to support VS 2008 any longer.

Of course that's this project's decision to make, but that's very unfortunate for me. gevent needs to continue to support Python 2.7 for some time to come. It's not like a switch was flipped and usage of Python 2.7 just stopped — it still makes up more than a quarter of gevent's 3 million monthly downloads. While direct upstream support may have ended, distributors such as Anaconda and RHEL are continuing to offer support (through 2024 in the latter case).
