### ISSUE TITLE
Android: multiple definition of uv_get_free_memory, uv_get_total_memory

### ISSUE THREAD

**Issue by marekfoltyn** [libuv/libuv#2357]
Hello, 
recently I included libuv 1.30.0 to my Android project as native library using CMake's `add_subdirectory()`. During compilation, the following error appeared:
```
error: (...)/uv/CMakeFiles/uv.dir/src/unix/sysinfo-memory.c.o: multiple definition of 'uv_get_free_memory'
(...)/uv/CMakeFiles/uv.dir/src/unix/linux-core.c.o: previous definition here
error: (...)/uv/CMakeFiles/uv.dir/src/unix/sysinfo-memory.c.o: multiple definition of 'uv_get_total_memory'
(...)/libs/uv/CMakeFiles/uv.dir/src/unix/linux-core.c.o: previous definition here
```
When I commented out the `src/unix/sysinfo-memory.c` file from "android sources" in `CMakeLists.txt`, compilation succeeded. Is there a problem in libuv `CMakeLists.txt` or is it caused by a bad configuration in my project?
Thank you very much for any help.
Marek

* **Version**: 1.30.0
* **Platform**: Android

**Comment by bnoordhuis** [comment]
That's probably a bug I introduced in commit 7e6681f73. Am I right this patch fixes it?
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index f2ed3722..a34e5a1b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -260,8 +260,7 @@ if(CMAKE_SYSTEM_NAME STREQUAL "Android")
        src/unix/linux-syscalls.c
        src/unix/procfs-exepath.c
        src/unix/pthread-fixes.c
-       src/unix/sysinfo-loadavg.c
-       src/unix/sysinfo-memory.c)
+       src/unix/sysinfo-loadavg.c)
 endif()
 
 if(APPLE OR CMAKE_SYSTEM_NAME MATCHES "Android|Linux|OS/390")
```

**Comment by marekfoltyn** [comment]
Yes, in my case it solves the issue. I hope it does not break something else. Thank you.

**Comment by bnoordhuis** [comment]
Thanks for confirming, I've opened #2316.

I was pleased (what's in word) to find out the bug was actually introduced only a few weeks ago, in v1.29.0. It would have been disheartening if it had gone unnoticed for over year.

**Comment by AuTsing** [comment]
It works.
