### ISSUE TITLE
Failed build iOS on macOS

### ISSUE THREAD

**Issue by caobug** [libuv/libuv#2975]
Prev version is ok.

* **Version**: 1.39.0
* **Platform**: iOS cross compile tools: ios-cmake

```
libuv-1.39.0/src/unix/darwin.c:190:28: error: a parameter list without types is only allowed in a function definition
  void (*pIOObjectRelease)(io_object_t);
                           ^
libuv-1.39.0/src/unix/darwin.c:192:3: error: implicit declaration of function 'CFMutableDictionaryRef' [-Werror,-Wimplicit-function-declaration]
  CFMutableDictionaryRef (*pIOServiceMatching)(const char*);
  ^
libuv-1.39.0/src/unix/darwin.c:192:28: error: use of undeclared identifier 'pIOServiceMatching'
  CFMutableDictionaryRef (*pIOServiceMatching)(const char*);
                           ^
libuv-1.39.0/src/unix/darwin.c:192:48: error: expected expression
  CFMutableDictionaryRef (*pIOServiceMatching)(const char*);
                                               ^
libuv-1.39.0/src/unix/darwin.c:194:50: warning: declaration specifier missing, defaulting to 'int'
                                                 CFMutableDictionaryRef,
                                                 ^
                                                 int
libuv-1.39.0/src/unix/darwin.c:195:50: error: unknown type name 'io_iterator_t'
                                                 io_iterator_t*);
                                                 ^
libuv-1.39.0/src/unix/darwin.c:196:3: error: implicit declaration of function 'io_service_t' [-Werror,-Wimplicit-function-declaration]
  io_service_t (*pIOIteratorNext)(io_iterator_t);
  ^
libuv-1.39.0/src/unix/darwin.c:196:18: error: use of undeclared identifier 'pIOIteratorNext'
  io_service_t (*pIOIteratorNext)(io_iterator_t);
                 ^
libuv-1.39.0/src/unix/darwin.c:196:35: error: use of undeclared identifier 'io_iterator_t'
  io_service_t (*pIOIteratorNext)(io_iterator_t);
                                  ^
libuv-1.39.0/src/unix/darwin.c:197:3: error: implicit declaration of function 'CFTypeRef' [-Werror,-Wimplicit-function-declaration]
  CFTypeRef (*pIORegistryEntryCreateCFProperty)(io_registry_entry_t,
  ^
libuv-1.39.0/src/unix/darwin.c:197:15: error: use of undeclared identifier 'pIORegistryEntryCreateCFProperty'
  CFTypeRef (*pIORegistryEntryCreateCFProperty)(io_registry_entry_t,
              ^
libuv-1.39.0/src/unix/darwin.c:197:49: error: use of undeclared identifier 'io_registry_entry_t'
  CFTypeRef (*pIORegistryEntryCreateCFProperty)(io_registry_entry_t,
                                                ^
libuv-1.39.0/src/unix/darwin.c:198:49: error: use of undeclared identifier 'CFStringRef'
                                                CFStringRef,
                                                ^
libuv-1.39.0/src/unix/darwin.c:199:49: error: use of undeclared identifier 'CFAllocatorRef'
                                                CFAllocatorRef,
                                                ^
libuv-1.39.0/src/unix/darwin.c:200:49: error: use of undeclared identifier 'IOOptionBits'
                                                IOOptionBits);
                                                ^
libuv-1.39.0/src/unix/darwin.c:203:3: error: implicit declaration of function 'CFStringRef' [-Werror,-Wimplicit-function-declaration]
  CFStringRef (*pCFStringCreateWithCString)(CFAllocatorRef,
  ^
libuv-1.39.0/src/unix/darwin.c:203:17: error: use of undeclared identifier 'pCFStringCreateWithCString'
  CFStringRef (*pCFStringCreateWithCString)(CFAllocatorRef,
                ^
libuv-1.39.0/src/unix/darwin.c:204:45: error: expected expression
                                            const char*,
                                            ^
libuv-1.39.0/src/unix/darwin.c:203:45: error: use of undeclared identifier 'CFAllocatorRef'
  CFStringRef (*pCFStringCreateWithCString)(CFAllocatorRef,
                                            ^
libuv-1.39.0/src/unix/darwin.c:205:45: error: use of undeclared identifier 'CFStringEncoding'
                                            CFStringEncoding);
                                            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
libuv-1.39.0/src/unix/darwin.c:190:28: error: a parameter list without types is only allowed in a function definition
  void (*pIOObjectRelease)(io_object_t);
                           ^
libuv-1.39.0/src/unix/darwin.c:192:3: error: implicit declaration of function 'CFMutableDictionaryRef' [-Werror,-Wimplicit-function-declaration]
  CFMutableDictionaryRef (*pIOServiceMatching)(const char*);
  ^
make[2]: *** [CMakeFiles/uv.dir/src/unix/darwin.c.o] Error 1
make[1]: *** [CMakeFiles/uv.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
libuv-1.39.0/src/unix/darwin.c:192:28: error: use of undeclared identifier 'pIOServiceMatching'
  CFMutableDictionaryRef (*pIOServiceMatching)(const char*);
                           ^
libuv-1.39.0/src/unix/darwin.c:192:48: error: expected expression
  CFMutableDictionaryRef (*pIOServiceMatching)(const char*);
                                               ^
libuv-1.39.0/src/unix/darwin.c:194:50: warning: declaration specifier missing, defaulting to 'int'
                                                 CFMutableDictionaryRef,
                                                 ^
                                                 int
libuv-1.39.0/src/unix/darwin.c:195:50: error: unknown type name 'io_iterator_t'
                                                 io_iterator_t*);
                                                 ^
libuv-1.39.0/src/unix/darwin.c:196:3: error: implicit declaration of function 'io_service_t' [-Werror,-Wimplicit-function-declaration]
  io_service_t (*pIOIteratorNext)(io_iterator_t);
  ^
libuv-1.39.0/src/unix/darwin.c:196:18: error: use of undeclared identifier 'pIOIteratorNext'
  io_service_t (*pIOIteratorNext)(io_iterator_t);
                 ^
libuv-1.39.0/src/unix/darwin.c:196:35: error: use of undeclared identifier 'io_iterator_t'
  io_service_t (*pIOIteratorNext)(io_iterator_t);
                                  ^
libuv-1.39.0/src/unix/darwin.c:197:3: error: implicit declaration of function 'CFTypeRef' [-Werror,-Wimplicit-function-declaration]
  CFTypeRef (*pIORegistryEntryCreateCFProperty)(io_registry_entry_t,
  ^
libuv-1.39.0/src/unix/darwin.c:197:15: error: use of undeclared identifier 'pIORegistryEntryCreateCFProperty'
  CFTypeRef (*pIORegistryEntryCreateCFProperty)(io_registry_entry_t,
              ^
libuv-1.39.0/src/unix/darwin.c:197:49: error: use of undeclared identifier 'io_registry_entry_t'
  CFTypeRef (*pIORegistryEntryCreateCFProperty)(io_registry_entry_t,
                                                ^
libuv-1.39.0/src/unix/darwin.c:198:49: error: use of undeclared identifier 'CFStringRef'
                                                CFStringRef,
                                                ^
libuv-1.39.0/src/unix/darwin.c:199:49: error: use of undeclared identifier 'CFAllocatorRef'
                                                CFAllocatorRef,
                                                ^
libuv-1.39.0/src/unix/darwin.c:200:49: error: use of undeclared identifier 'IOOptionBits'
                                                IOOptionBits);
                                                ^
libuv-1.39.0/src/unix/darwin.c:203:3: error: implicit declaration of function 'CFStringRef' [-Werror,-Wimplicit-function-declaration]
  CFStringRef (*pCFStringCreateWithCString)(CFAllocatorRef,
  ^
libuv-1.39.0/src/unix/darwin.c:203:17: error: use of undeclared identifier 'pCFStringCreateWithCString'
  CFStringRef (*pCFStringCreateWithCString)(CFAllocatorRef,
                ^
libuv-1.39.0/src/unix/darwin.c:204:45: error: expected expression
                                            const char*,
                                            ^
libuv-1.39.0/src/unix/darwin.c:203:45: error: use of undeclared identifier 'CFAllocatorRef'
  CFStringRef (*pCFStringCreateWithCString)(CFAllocatorRef,
                                            ^
libuv-1.39.0/src/unix/darwin.c:205:45: error: use of undeclared identifier 'CFStringEncoding'
                                            CFStringEncoding);
```

**Comment by bnoordhuis** [comment]
That's caused by 87f076515937345fda1a1dbc598f34e65e1b81c7. Can you try this patch?
```diff
diff --git a/src/unix/darwin.c b/src/unix/darwin.c
index d0ecd452..76a7ae15 100644
--- a/src/unix/darwin.c
+++ b/src/unix/darwin.c
@@ -33,9 +33,7 @@
 #include <sys/sysctl.h>
 #include <unistd.h>  /* sysconf */
 
-#if !TARGET_OS_IPHONE
 #include "darwin-stub.h"
-#endif
 
 static uv_once_t once = UV_ONCE_INIT;
 static uint64_t (*time_func)(void);
```

**Comment by cjihrig** [comment]
Ping @caobug. There is a new release coming soon, and it would be good to fix this if possible.

**Comment by evanlucas** [comment]
@bnoordhuis I was just able to cross compile with your patch

**Comment by Diatrus** [comment]
@caobug this can be closed, it was fixed in #3106
