### PR TITLE
Add recvmmsg and sendmmsg support

### PR DESCRIPTION
**Pull request by oerdnj**
This PR adds support for using recvmmsg() and sendmmsg() on platforms that support the extended system call.

### CODE REVIEW

File: src/unix/udp.c [hunk 1]
```diff
@@ -207,13 +268,93 @@ static void uv__udp_recvmsg(uv_udp_t* handle) {
...
+}
 
 static void uv__udp_sendmsg(uv_udp_t* handle) {
   uv_udp_send_t* req;
-  QUEUE* q;
   struct msghdr h;
+  QUEUE* q;
   ssize_t size;
 
+  /* TODO: Test of uv_sendmmsg just once */
```
Comment (cjihrig) [inline src/unix/udp.c]: Can you add your name to the TODO.

File: src/unix/udp.c [hunk 2]
```diff
@@ -148,6 +152,52 @@ static void uv__udp_io(uv_loop_t* loop, uv__io_t* w, unsigned int revents) {
...
+    msgs[k].msg_hdr.msg_iov = iov + k;
+    msgs[k].msg_hdr.msg_iovlen = 1;
+    msgs[k].msg_hdr.msg_name = peers + k;
+    msgs[k].msg_hdr.msg_namelen = sizeof(peers[0]);
+  }
+
+  do {
+    nread = uv__recvmmsg(handle->io_watcher.fd, msgs, chunks, 0, NULL);
+  }
+  while (nread == -1 && errno == EINTR);
```
Comment (cjihrig) [inline src/unix/udp.c]: Can you move this to the previous line.

File: src/unix/udp.c [hunk 3]
```diff
@@ -148,6 +152,52 @@ static void uv__udp_io(uv_loop_t* loop, uv__io_t* w, unsigned int revents) {
...
+
+  if (nread < 1) {
+    if (nread == 0 || errno == EAGAIN || errno == EWOULDBLOCK)
+      handle->recv_cb(handle, 0, buf, NULL, 0);
+    else
+      handle->recv_cb(handle, -errno, buf, NULL, 0);
```
Comment (cjihrig) [inline src/unix/udp.c]:
```suggestion
      handle->recv_cb(handle, UV__ERR(errno), buf, NULL, 0);
```

File: src/unix/udp.c [hunk 4]
```diff
@@ -167,13 +217,24 @@ static void uv__udp_recvmsg(uv_udp_t* handle) {
...
-    handle->alloc_cb((uv_handle_t*) handle, 64 * 1024, &buf);
+    handle->alloc_cb((uv_handle_t*) handle, UDP_DGRAM_MAXSIZE, &buf);
     if (buf.base == NULL || buf.len == 0) {
       handle->recv_cb(handle, UV_ENOBUFS, &buf, NULL, 0);
       return;
     }
     assert(buf.base != NULL);
 
+    /* TODO: test of recvmmsg support just once */
+    uv__recvmmsg(handle->io_watcher.fd, NULL, 0, 0, NULL);
```
Comment (cjihrig) [inline src/unix/udp.c]: Could you prefer using an explicit return value over `errno` when possible.

Comment (oerdnj) [reply src/unix/udp.c]: Fixed in `uv__udp_mmsg_init()`

File: src/unix/udp.c (hunk 1 above)
Comment (oerdnj) [reply src/unix/udp.c]: I rather wrote the code, not sure if the naming is right:
```
static int uv__recvmmsg_avail = 0;
static int uv__sendmmsg_avail = 0;
```
but naming is the hardest part of CS :).

File: src/unix/udp.c (hunk 3 above)
Comment (oerdnj) [reply src/unix/udp.c]: Fixed.

**Comment by oerdnj** [comment]
@cjihrig Thanks for the review.

The only part I am truly unsure is the part where I walk the `QUEUE*` twice in the `uv__udp_sendmmsg()`.  Does the `QUEUE*` has only one consumer/producer at a time?

The other solution might be to create extra local `QUEUE*` where the first loop will move the members and then after the sending it will move the members back either to `handle->write_queue` or to `handle->write_completed_queue`. Not sure if that's necessary though.

**Comment by oerdnj** [comment]
I added all the changes as fixup commits for easier review.  Just tell me when you want to rebase and squash the fixup commits.

File: src/unix/udp.c [hunk 5]
```diff
@@ -148,6 +166,51 @@ static void uv__udp_io(uv_loop_t* loop, uv__io_t* w, unsigned int revents) {
...
+  }
+  else {
+    /* count to zero, so the buffer base comes last */
+    for (k = nread; k-- && handle->recv_cb != NULL;) {
+      flags = 0;
+      if (msgs[k].msg_hdr.msg_flags & MSG_TRUNC)
+        flags |= UV_UDP_PARTIAL;
+
+      chunk_buf = uv_buf_init(iov[k].iov_base, iov[k].iov_len);
+      handle->recv_cb(handle, msgs[k].msg_len, &chunk_buf, msgs[k].msg_hdr.msg_name, flags);
```
Comment (saghul) [inline src/unix/udp.c]: Generally alloc_cb and recv_cb come in pairs, wouldn't this break that assumption?

File: src/unix/udp.c [hunk 6]
```diff
@@ -167,13 +230,23 @@ static void uv__udp_recvmsg(uv_udp_t* handle) {
...
       handle->recv_cb(handle, UV_ENOBUFS, &buf, NULL, 0);
       return;
     }
     assert(buf.base != NULL);
 
+    uv_once(&once, uv__udp_mmsg_init);
+    if (uv__recvmmsg_avail) {
+      /* Returned space for more than 1 datagram, use it to receive
+       * multiple datagrams. */
+      if (buf.len >= 2 * UDP_DGRAM_MAXSIZE) {
```
Comment (saghul) [inline src/unix/udp.c]: wouldn't checking for `> UDP_DGRAM_MAXSIZE` suffice?

**Comment by saghul** [comment]
Ping?

**Comment by oerdnj** [comment]
We were finishing BIND 9.16 release for two last months (and I am on PTO this week). I’ll schedule some time for this and the other issue (TFO) in February, ok?

**Comment by saghul** [comment]
Sounds excellent!

File: src/unix/udp.c (hunk 6 above)
Comment (wupeka) [reply src/unix/udp.c]: If buf.len is not at least 2*UDP_DGRAM_MAXSIZE then we still will be able to receive just 1 chunk, and there'll be no gain from recvmmsg

File: src/unix/udp.c [hunk 7]
```diff
@@ -148,6 +166,51 @@ static void uv__udp_io(uv_loop_t* loop, uv__io_t* w, unsigned int revents) {
...
+  int flags;
+  int k;
+
+  /* prepare structures for recvmmsg */
+  chunks = buf->len / UDP_DGRAM_MAXSIZE;
+  if (chunks > MMSG_MAXWIDTH)
+    chunks = MMSG_MAXWIDTH;
+  for (k = 0; k < chunks; ++k) {
+    iov[k].iov_base = buf->base + k * UDP_DGRAM_MAXSIZE;
+    iov[k].iov_len = UDP_DGRAM_MAXSIZE;
```
[the remark this answers is not in the document]
Comment (wupeka) [reply src/unix/udp.c]: There would be an unused part of the buffer at the end of it.

File: src/unix/udp.c [hunk 8]
```diff
@@ -167,13 +230,23 @@ static void uv__udp_recvmsg(uv_udp_t* handle) {
...
     }
     assert(buf.base != NULL);
 
+    uv_once(&once, uv__udp_mmsg_init);
+    if (uv__recvmmsg_avail) {
+      /* Returned space for more than 1 datagram, use it to receive
+       * multiple datagrams. */
+      if (buf.len >= 2 * UDP_DGRAM_MAXSIZE) {
+        uv__udp_recvmmsg(handle, &buf);
+        return;
```
Comment (wupeka) [inline src/unix/udp.c]: I'd allow multiple uv__udp_recvmmsg to be run - have uv__udp_recvmmsg return number of packets received and subtracting it from `count` until we get it to 0 (same as with regular recvmsg, to void loop startvation) - otherwise if we get a constant stream of packets we have to rearm event loop every time.

File: src/unix/udp.c (hunk 6 above)
Comment (saghul) [reply src/unix/udp.c]: gotcha

**Comment by saghul** [comment]
Thanks @wupeka , looks like this commit https://github.com/libuv/libuv/pull/2532/commits/22db2a0494d6194a85095fc56e203ab8dcac11df is causing conflicts. Was its inclusion intentional? If so, I'd rather have it as a separate PR, since it has nothing to do with UDP.

**Comment by wupeka** [comment]
@saghul Sorry for the mistake, this commit is a part of https://github.com/libuv/libuv/pull/2559 that I put there by accident, fixed.

**Comment by saghul** [comment]
@wupeka oh, thanks!

File: src/unix/udp.c (hunk 5 above)
Comment (wupeka) [reply src/unix/udp.c]: It does. I added a special flag passed to recv_cb to signal that this buffer is a part of a larger buffer and must not be freed.

File: CMakeLists.txt [hunk 9]
```diff
@@ -32,6 +32,7 @@ set(uv_sources
     src/version.c)
 
 set(uv_test_sources
+    test/benchmark-ping-udp.c
```
[the remark this answers is not in the document]
Comment (oerdnj) [reply CMakeLists.txt]: Done in d64847d2

File: src/unix/udp.c (hunk 8 above)
Comment (oerdnj) [reply src/unix/udp.c]: Sure, that sounds reasonable. Are you going to implement it? :-)

File: src/unix/udp.c (hunk 5 above)
Comment (saghul) [reply src/unix/udp.c]: 👍

File: src/unix/udp.c [hunk 10]
```diff
@@ -148,6 +172,54 @@ static void uv__udp_io(uv_loop_t* loop, uv__io_t* w, unsigned int revents) {
...
+  } while (nread == -1 && errno == EINTR);
+
+  if (nread < 1) {
+    if (nread == 0 || errno == EAGAIN || errno == EWOULDBLOCK)
+      handle->recv_cb(handle, 0, buf, NULL, 0);
+    else
+      handle->recv_cb(handle, UV__ERR(errno), buf, NULL, 0);
+  }
+  else {
+    /* count to zero, so the buffer base comes last */
```
Comment (saghul) [inline src/unix/udp.c]: Does this imply that the buffers are passed to the application in reverse order? do you foresee any problem with it?

**Comment by saghul** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1739/

File: src/unix/udp.c (hunk 10 above)
Comment (wupeka) [reply src/unix/udp.c]: 1. Yes, so that the client can free the buffer when it receives the callback without the flag set
2. It's UDP - order is not guaranteed in any way.

**Comment by oerdnj** [comment]
@saghul Thank you very much!

**Comment by saghul** [comment]
Looks like there are some legit failures:

```
../src/unix/udp.c:68:9: warning: implicit declaration of function 'uv__recvmmsg' [-Wimplicit-function-declaration]
  ret = uv__recvmmsg(s, NULL, 0, 0, NULL);
        ^
../src/unix/udp.c:71:9: warning: implicit declaration of function 'uv__sendmmsg' [-Wimplicit-function-declaration]
  ret = uv__sendmmsg(s, NULL, 0, 0);
        ^
../src/unix/udp.c:176:29: error: use of undeclared identifier 'UV__MMSG_MAXWIDTH'
  struct sockaddr_in6 peers[UV__MMSG_MAXWIDTH];
                            ^
../src/unix/udp.c:177:20: error: use of undeclared identifier 'UV__MMSG_MAXWIDTH'
  struct iovec iov[UV__MMSG_MAXWIDTH];
                   ^
../src/unix/udp.c:178:27: error: use of undeclared identifier 'UV__MMSG_MAXWIDTH'
  struct uv__mmsghdr msgs[UV__MMSG_MAXWIDTH];
                          ^
../src/unix/udp.c:187:16: error: use of undeclared identifier 'UV__MMSG_MAXWIDTH'
  if (chunks > UV__MMSG_MAXWIDTH)
```

**Comment by oerdnj** [comment]
@saghul Sorry, seems like combination of typo and never testing on anything else than Linux.

I've just successfully compiled ed1d760 on macOS, could you please run your CI again?

**Comment by saghul** [comment]
Here we go again: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1740/

**Comment by oerdnj** [comment]
Thank you, if fixed the code error, but I and @wupeka will look at the test failures. Those should not be happening, I get the assertion failure even on macOS:
```
not ok 352 - udp_open_connect
# exit code 6
# Output from process `udp_open_connect`: (no output)
Output from process `udp_open_connect`:
# Assertion failed in test/test-udp-open.c on line 278: r == 0
```

**Comment by oerdnj** [comment]
The error I am seeing on macOS is caused by 203e3071b99d7abfa8d228dea4938ab63ac3cb16

**Comment by oerdnj** [comment]
@saghul one more run, please.

**Comment by saghul** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1742/

**Comment by saghul** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1743/

**Comment by saghul** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1744/

**Comment by oerdnj** [comment]
@saghul how reliable is the CI? The failures in the last run seems to be unrelated to the changes in this PR.

**Comment by saghul** [comment]
> @saghul how reliable is the CI? The failures in the last run seems to be unrelated to the changes in this PR.

Some tests are flaky, alas.

@libuv/collaborators does anyone want to take a look here? I think this is good to go!

**Comment by oerdnj** [comment]
Also let me express we (ISC) are committed to keep any bugs in this in the future. It's not just a dump & forget.

**Comment by oerdnj** [comment]
@santigimeno Thank you, I resolved all the style nits, and improved the commit description.

**Comment by oerdnj** [comment]
@saghul Can you please fire up the CI now, so we do last check?

I tested this on Debian 10 and macOS by hand and I don't have more systems at my disposal.

**Comment by saghul** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1747/

**Comment by oerdnj** [comment]
> > CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1747/
> 
> oerdnj is missing the Overall/Read permission

Something has happened since yesterday.

**Comment by saghul** [comment]
Ah, the CI is under embargo, but I can still see it. It looks 💚  (modulo unrelated failures).

**Comment by oerdnj** [comment]
So what happens now?  (I am genuinely asking what's the process to get it finally merged?)

**Comment by santigimeno** [comment]
It should be merged shortly. Being not a trivial change we usually wait a little for other collaborators to chime in.

**Comment by saghul** [comment]
I’ll merge on Monday if nobody has any objections. Amazing work folks!

File: src/unix/udp.c [hunk 11]
```diff
@@ -199,21 +291,115 @@ static void uv__udp_recvmsg(uv_udp_t* handle) {
...
+      assert(req != NULL);
+
+      req->status = UV__ERR(errno);
+      QUEUE_REMOVE(&req->queue);
+      QUEUE_INSERT_TAIL(&handle->write_completed_queue, &req->queue);
+    }
+    uv__io_feed(handle->loop, &handle->io_watcher);
+    return;
+  }
+  for (i = 0, q = QUEUE_HEAD(&handle->write_queue);
```
Comment (bnoordhuis) [inline src/unix/udp.c]: Maybe put a blank line here and on line 381 for legibility.

File: test/benchmark-ping-udp.c [hunk 12]
```diff
@@ -0,0 +1,161 @@
...
+static void buf_free(const uv_buf_t* buf) {
+}
+
+
+static void pinger_close_cb(uv_handle_t* handle) {
+  pinger_t* pinger;
+
+  pinger = (pinger_t*)handle->data;
+#if DEBUG
+  fprintf(stderr, "ping_pongs: %d roundtrips/s\n", pinger->pongs / (TIME / 1000));
```
Comment (bnoordhuis) [inline test/benchmark-ping-udp.c]: Long line (although I suspect this got copied from somewhere else.)

File: test/benchmark-ping-udp.c [hunk 13]
```diff
@@ -0,0 +1,161 @@
...
+    FATAL("uv_udp_read_start failed");
+  }
+  pinger_write_ping(pinger);
+}
+
+static int ping_udp(unsigned pingers) {
+  loop = uv_default_loop();
+  start_time = uv_now(loop);
+
+  unsigned i;
```
Comment (bnoordhuis) [inline test/benchmark-ping-udp.c]: Can you put this at the top of the function?

File: src/unix/udp.c [hunk 14]
```diff
@@ -148,6 +177,55 @@ static void uv__udp_io(uv_loop_t* loop, uv__io_t* w, unsigned int revents) {
...
+    iov[k].iov_len = UV__UDP_DGRAM_MAXSIZE;
+    msgs[k].msg_hdr.msg_iov = iov + k;
+    msgs[k].msg_hdr.msg_iovlen = 1;
+    msgs[k].msg_hdr.msg_name = peers + k;
+    msgs[k].msg_hdr.msg_namelen = sizeof(peers[0]);
+  }
+
+  do {
+    nread = uv__recvmmsg(handle->io_watcher.fd, msgs, chunks, 0, NULL);
+  } while (nread == -1 && errno == EINTR);
```
Comment (bnoordhuis) [inline src/unix/udp.c]: Tiniest of nits: can you drop the braces?

File: src/unix/udp.c [hunk 15]
```diff
@@ -167,13 +245,27 @@ static void uv__udp_recvmsg(uv_udp_t* handle) {
...
 
+#if HAVE_MMSG
+    uv_once(&once, uv__udp_mmsg_init);
+    if (uv__recvmmsg_avail) {
+      /* Returned space for more than 1 datagram, use it to receive
+       * multiple datagrams. */
+      if (buf.len >= 2 * UV__UDP_DGRAM_MAXSIZE) {
+        nread = uv__udp_recvmmsg(handle, &buf);
+        if (nread > 0)
+          count -= nread;
```
Comment (bnoordhuis) [inline src/unix/udp.c]: Checking to be sure: `nread` is the number of datagrams, not bytes, correct?

File: src/unix/udp.c [hunk 16]
```diff
@@ -167,13 +245,27 @@ static void uv__udp_recvmsg(uv_udp_t* handle) {
...
-    handle->alloc_cb((uv_handle_t*) handle, 64 * 1024, &buf);
+    handle->alloc_cb((uv_handle_t*) handle, UV__UDP_DGRAM_MAXSIZE, &buf);
     if (buf.base == NULL || buf.len == 0) {
       handle->recv_cb(handle, UV_ENOBUFS, &buf, NULL, 0);
       return;
     }
     assert(buf.base != NULL);
 
+#if HAVE_MMSG
+    uv_once(&once, uv__udp_mmsg_init);
```
[the remark this answers is not in the document]
Comment (oerdnj) [reply src/unix/udp.c]: A very synthetic benchmark:
```
#include <assert.h>
#include <uv.h>
#include <stdio.h>
#include <stddef.h>
#include <stdint.h>
#include <time.h>
#include <inttypes.h>

static uv_once_t once = UV_ONCE_INIT;

#ifndef clock_gettime_nsec_np

#define NSEC_PER_USEC	1000L
#define NSEC_PER_SEC	1000000000L

#define timeval2nsec(tv) (tv.tv_sec * NSEC_PER_SEC + tv.tv_nsec)

uint64_t
clock_gettime_nsec_np(clockid_t clock_id)
{
	struct timespec tv;
	assert(clock_gettime(clock_id, &tv) == 0);
	return timeval2nsec(tv);
}
#endif

void init(void) {
	fprintf(stderr, "once\n");
}

int main(void)
{
	uint64_t t1, t2, t3;

	size_t max = UINT16_MAX << 14;

	t1 = clock_gettime_nsec_np(CLOCK_MONOTONIC_RAW);
	for (size_t i = 0; i < max; i++) {
		uv_once(&once, init);
		putchar_unlocked('a');
	}
	t2 = clock_gettime_nsec_np(CLOCK_MONOTONIC_RAW);
	for (size_t i = 0; i < max; i++) {
		putchar_unlocked('a');
	}
	t3 = clock_gettime_nsec_np(CLOCK_MONOTONIC_RAW);

	uint64_t d1 = t2 - t1;
	uint64_t d2 = t3 - t2;

	fprintf(stderr, "Repeats: %zu\n", max);
	fprintf(stderr, "D1 nsec=%" PRIu64 " (%" PRIu64 ")\n", d1, d1 / max);
	fprintf(stderr, "D2 nsec=%" PRIu64 " (%" PRIu64 ")\n", d2, d2 / max);
	fprintf(stderr, "uv_once() nsec=%" PRIu64 " (%" PRIu64 ")\n", d1 - d2, d1/max - d2/max);
}
```

shows ~0-1nsec slowdown on macOS
```
$ gcc -O2 -g a.c -luv && ./a.out > /dev/null
once
Repeats: 1073725440
D1 nsec=5649904724 (5)
D2 nsec=4518916115 (4)
uv_once() nsec=1130988609 (1)
```

and similar numbers on Linux:
```
$ gcc -O2 -g a.c -luv && ./a.out > /dev/null
once
Repeats: 1073725440
D1 nsec=3794652959 (3)
D2 nsec=2202632143 (2)
uv_once() nsec=1592020816 (1)
```

with `-O0` it shows some bigger slowdown on macOS:
```
$ gcc -O0 -g a.c -luv && ./a.out > /dev/null
once
Repeats: 1073725440
D1 nsec=7374758838 (6)
D2 nsec=3486789750 (3)
uv_once() nsec=3887969088 (3)
```

and Linux:
```
$ gcc -O0 -g a.c -luv && ./a.out > /dev/null
once
Repeats: 1073725440
D1 nsec=6038305056 (5)
D2 nsec=2622438418 (2)
uv_once() nsec=3415866638 (3)
```

But still in ~3nsec ballpark.

File: src/unix/udp.c (hunk 15 above)
Comment (oerdnj) [reply src/unix/udp.c]: > RETURN VALUE
>       On success, recvmmsg() returns the number of messages received in msgvec; on error, -1 is returned, and errno is set to indicate the error.

File: test/benchmark-ping-udp.c (hunk 12 above)
Comment (oerdnj) [reply test/benchmark-ping-udp.c]: Resolved in 478aa6d8

Comment (oerdnj) [reply test/benchmark-ping-udp.c]: Resolved in 478aa6d8

File: docs/src/udp.rst [hunk 17]
```diff
@@ -62,12 +68,14 @@ Data types
...
-      ``UV_UDP_PARTIAL`` is used.
+    * `flags`: One or more or'ed UV_UDP_* constants.
 
     The callee is responsible for freeing the buffer, libuv does not reuse it.
     The buffer may be a null buffer (where `buf->base` == NULL and `buf->len` == 0)
-    on error.
+    on error. If UV_UDP_MMSG_CHUNK is set then the buffer passed is not
+    the first part of a larger buffer allocated as a whole by alloc_cb for
+    recvmmsg and it must not be freed - the whole buffer can be freed when
+    recv_cb gets the first chunk, at the end, with this flag unset.
```
[the remark this answers is not in the document]
Comment (oerdnj) [reply docs/src/udp.rst]: Resolved in 8f521626

File: src/unix/udp.c (hunk 14 above)
Comment (oerdnj) [reply src/unix/udp.c]: Resolved in 8f521626

File: test/benchmark-ping-udp.c (hunk 13 above)
Comment (oerdnj) [reply test/benchmark-ping-udp.c]: 8f521626

File: src/unix/udp.c (hunk 11 above)
Comment (oerdnj) [reply src/unix/udp.c]: Resolved in 8f52162

File: src/unix/udp.c [hunk 18]
```diff
@@ -148,6 +177,55 @@ static void uv__udp_io(uv_loop_t* loop, uv__io_t* w, unsigned int revents) {
...
+    /* count to zero, so the buffer base comes last */
+    for (k = nread; k-- && handle->recv_cb != NULL;) {
+      flags = 0;
+      if (msgs[k].msg_hdr.msg_flags & MSG_TRUNC)
+        flags |= UV_UDP_PARTIAL;
+      if (k != 0)
+        flags |= UV_UDP_MMSG_CHUNK;
+
+      chunk_buf = uv_buf_init(iov[k].iov_base, iov[k].iov_len);
+      handle->recv_cb(handle, msgs[k].msg_len, &chunk_buf, msgs[k].msg_hdr.msg_name, flags);
```
[the remark this answers is not in the document]
Comment (oerdnj) [reply src/unix/udp.c]: Resolved in 8f52162

File: src/unix/udp.c [hunk 19]
```diff
@@ -148,6 +177,55 @@ static void uv__udp_io(uv_loop_t* loop, uv__io_t* w, unsigned int revents) {
...
+  struct uv__mmsghdr msgs[UV__MMSG_MAXWIDTH];
+  ssize_t nread;
+  uv_buf_t chunk_buf;
+  int chunks;
+  int flags;
+  int k;
+
+  /* prepare structures for recvmmsg */
+  chunks = buf->len / UV__UDP_DGRAM_MAXSIZE;
+  if (chunks > UV__MMSG_MAXWIDTH)
```
[the remark this answers is not in the document]
Comment (oerdnj) [reply src/unix/udp.c]: Resolved in 8f52162

File: src/unix/udp.c [hunk 20]
```diff
@@ -148,6 +177,55 @@ static void uv__udp_io(uv_loop_t* loop, uv__io_t* w, unsigned int revents) {
...
+  struct iovec iov[UV__MMSG_MAXWIDTH];
+  struct uv__mmsghdr msgs[UV__MMSG_MAXWIDTH];
+  ssize_t nread;
+  uv_buf_t chunk_buf;
+  int chunks;
+  int flags;
+  int k;
+
+  /* prepare structures for recvmmsg */
+  chunks = buf->len / UV__UDP_DGRAM_MAXSIZE;
```
[the remark this answers is not in the document]
Comment (oerdnj) [reply src/unix/udp.c]: Resolved in 8f52162

> (Don't forget to update the loop guard on line 215!)

Do you consider the underflow to be a problem?

```
    for (k = nread; k && handle->recv_cb != NULL;) {
      k--;
```
isn't that much more elegant.

File: src/unix/udp.c [hunk 21]
```diff
@@ -49,6 +51,33 @@ static int uv__udp_maybe_deferred_bind(uv_udp_t* handle,
...
+static void uv__udp_sendmmsg(uv_udp_t* handle);
+
+static int uv__recvmmsg_avail;
+static int uv__sendmmsg_avail;
+static uv_once_t once = UV_ONCE_INIT;
+
+static void uv__udp_mmsg_init(void) {
+  int ret;
+  int s;
+  s = uv__socket(AF_INET, SOCK_DGRAM, 0);
```
[the remark this answers is not in the document]
Comment (oerdnj) [reply src/unix/udp.c]: Resolved in 8f52162

File: src/unix/udp.c [hunk 22]
```diff
@@ -49,6 +51,33 @@ static int uv__udp_maybe_deferred_bind(uv_udp_t* handle,
...
+  if (s < 0)
+    return;
+  ret = uv__recvmmsg(s, NULL, 0, 0, NULL);
+  if (ret == 0 || errno != ENOSYS)
+    uv__recvmmsg_avail = 1;
+  ret = uv__sendmmsg(s, NULL, 0, 0);
```
[the remark this answers is not in the document]
Comment (oerdnj) [reply src/unix/udp.c]: Good catch, Resolved in 8f52162

File: src/unix/freebsd.c [hunk 23]
```diff
@@ -288,3 +288,28 @@ int uv_cpu_info(uv_cpu_info_t** cpu_infos, int* count) {
   uv__free(cp_times);
   return 0;
 }
+
+
+int uv__sendmmsg(int fd,
+                 struct uv__mmsghdr* mmsg,
+                 unsigned int vlen,
+                 unsigned int flags) {
+#if defined(__FreeBSD_kernel__) || defined(__FreeBSD__)
```
[the remark this answers is not in the document]
Comment (oerdnj) [reply src/unix/freebsd.c]: Good catch, Resolved in 8f52162 and 4ab37557

**Comment by oerdnj** [comment]
@bnoordhuis thank you for the review, I left two comments unresolved, I'll squash the fixup commits when the review is done.

File: src/unix/udp.c [hunk 24]
```diff
@@ -148,6 +180,60 @@ static void uv__udp_io(uv_loop_t* loop, uv__io_t* w, unsigned int revents) {
...
+  while (nread == -1 && errno == EINTR);
+
+  if (nread < 1) {
+    if (nread == 0 || errno == EAGAIN || errno == EWOULDBLOCK)
+      handle->recv_cb(handle, 0, buf, NULL, 0);
+    else
+      handle->recv_cb(handle, UV__ERR(errno), buf, NULL, 0);
+  } else {
+    /* count to zero, so the buffer base comes last */
+    for (k = nread; k && handle->recv_cb != NULL;) {
```
Comment (bnoordhuis) [inline src/unix/udp.c]:
```suggestion
    for (k = nread; k > 0 && handle->recv_cb != NULL;) {
```

File: src/unix/udp.c [hunk 25]
```diff
@@ -148,6 +180,60 @@ static void uv__udp_io(uv_loop_t* loop, uv__io_t* w, unsigned int revents) {
...
+        flags |= UV_UDP_PARTIAL;
+      if (k != 0)
+        flags |= UV_UDP_MMSG_CHUNK;
+
+      chunk_buf = uv_buf_init(iov[k].iov_base, iov[k].iov_len);
+      handle->recv_cb(handle,
+		      msgs[k].msg_len,
+		      &chunk_buf,
+		      msgs[k].msg_hdr.msg_name,
+		      flags);
```
Comment (bnoordhuis) [inline src/unix/udp.c]: Style nit: arguments should line up with the first argument.

File: src/unix/udp.c [hunk 26]
```diff
@@ -199,21 +299,120 @@ static void uv__udp_recvmsg(uv_udp_t* handle) {
...
+write_queue_drain:
+  for (pkts = 0, q = QUEUE_HEAD(&handle->write_queue);
+       pkts < UV__MMSG_MAXWIDTH && q != &handle->write_queue;
+       ++pkts, q = QUEUE_HEAD(q)) {
+    assert(q != NULL);
+    req = QUEUE_DATA(q, uv_udp_send_t, queue);
+    assert(req != NULL);
+
+    p = &h[pkts];
+    memset(p, 0, sizeof(h[pkts]));
```
Comment (bnoordhuis) [inline src/unix/udp.c]:
```suggestion
    memset(p, 0, sizeof(*p));
```
Looks a little more obviously correct to me.

File: src/unix/udp.c [hunk 27]
```diff
@@ -49,6 +51,36 @@ static int uv__udp_maybe_deferred_bind(uv_udp_t* handle,
...
+static void uv__udp_sendmmsg(uv_udp_t* handle);
+
+static int uv__recvmmsg_avail;
+static int uv__sendmmsg_avail;
+static uv_once_t once = UV_ONCE_INIT;
+
+static void uv__udp_mmsg_init(void) {
+  int ret;
+  int s;
+  s = uv__socket(AF_INET, SOCK_DGRAM, SOCK_CLOEXEC);
```
Comment (wupeka) [inline src/unix/udp.c]: The third parameter is protocol, it should be 0. (SOCK_CLOEXEC is already set in uv__socket).

File: src/unix/udp.c (hunk 25 above)
Comment (oerdnj) [reply src/unix/udp.c]: done

File: src/unix/udp.c (hunk 24 above)
Comment (oerdnj) [reply src/unix/udp.c]: Done

File: src/unix/udp.c (hunk 26 above)
Comment (oerdnj) [reply src/unix/udp.c]: Done.

**Comment by oerdnj** [comment]
Fixed the nits, rebased and squashed the fixup commits.

**Comment by saghul** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1757/

**Comment by oerdnj** [comment]
Looks like only one unrelated failure happened on centos 6:
> not ok 140 - ipc_closed_handle
> # timeout
> # Output from process `ipc_closed_handle`:
> # Assertion failed in test/test-ipc.c on line 601: status == 0

**Comment by saghul** [comment]
landed in 618533b7e3ba4b9e86d870a4ab59f147fa20566b, 56598f3d10fbb48705bba3149c995092d832bb62 and 3d7136639a39db46bc4a9074922559a564e49514. Nice work everyone!

**Comment by vcunat** [comment]
> Don’t free the buffer when the UV_UDP_MMSG_CHUNK flag is set.

Isn't that a slightly incompatible change to the public API of `uv_udp_recv_cb`?  Sure, most current users probably didn't provide a buffer longer than 64k so they shouldn't be running into that case (if I read it correctly), but it still makes me slightly uncomfortable.

**Comment by saghul** [comment]
Do you have an alternative proposal?

**Comment by vcunat** [comment]
I didn't get so far yet :-)  It's also a bit problematic that I only discovered this PR after it being released.

**Comment by vcunat** [comment]
Perhaps use the recvmmsg path only if explicitly turned on?  Say, extend `if (uv__recvmmsg_avail)` condition with an additional flag is set on the handle?

**Comment by saghul** [comment]
> Perhaps use the recvmmsg path only if explicitly turned on? Say, extend `if (uv__recvmmsg_avail)` condition with an additional flag on the handle?

That could be done with a flag to `uv_udp_init_ex` indeed.

**Comment by squeek502** [comment]
I'm a bit confused about why this didn't spark any changes in any test cases. Are there some unstated assumptions about when this flag is possible in `uv_udp_recv_cb` that the test cases are guaranteed not to hit?

For example, [here is an unconditional free of buf in a `udp_recv_cb`](https://github.com/libuv/libuv/blob/3d7136639a39db46bc4a9074922559a564e49514/test/benchmark-ping-udp.c#L111). Should it actually be checking for the `UV_UDP_MMSG_CHUNK`? If not, why not?

(disclaimer: I'm totally unfamiliar with `sendmmsg`/`recvmmsg`, I'm just going off the LibUV docs and wondering how to update [the luv bindings](https://github.com/luvit/luv/pull/471/commits/258b3debd368bed3e1f7c90b0ab270fc6fcd13ed))

**Comment by saghul** [comment]
There is a benchmark which uses a large enough buffer to enable the feature, on supported platforms. I agree that more tests would also be nice, so, if you're up for it, we'll gladly take a PR!

**Comment by vcunat** [comment]
> Isn't that a slightly incompatible change to the public API of `uv_udp_recv_cb`?

For reference, the incompatibility should be gone since v1.37.0 https://github.com/libuv/libuv/pull/2799

**Comment by vcunat** [comment]
sendmmsg() could also see some improvements, I think: https://github.com/libuv/libuv/issues/3129
