### ISSUE TITLE
Linux 2.6 deprecation/Undefined symbols: sendmmsg / recvmmsg when linking.

### ISSUE THREAD

**Issue by johnsonjh** [libuv/libuv#3871]
* See also: https://gitlab.com/dps8m/dps8m/-/issues/231
* **Version**:  1.44.3-dev (git)
* **Platform**:  Linux/SH4, uClibc-ng

This seems related to https://github.com/libuv/libuv/issues/3822 …

The DPS8M simulator (https://dps8m.gitlab.io/) is a user of libuv.

We produce automated builds via GitLab CI/CD that target many operating systems and architectures — see https://dps8m.gitlab.io/dps8m/Releases/ for our releases.  

The majority of our releases target Linux 2.6.32 as a minimum OS version, glibc 2.17 if glibc  is used, or the latest musl or uclibc-ng, depending on the target architecture.  For the convenience of our users, libuv is statically linked with our precompiled binaries.

Most users on most architectures will be using quite recent Linux kernels (and libcs) so this isn’t a problem. (In fact, the majority of Linux binaries we produce are static builds using musl-libc, which still supports Linux 2.6, although bumping our minimum Linux version requirement to 3.10 is planned for the next release.)

We did have one problem come up, post #3822 … On our Linux/SH4 builds (using uclibc-ng and targeting Linux 2.6.32) we are now failing to link dps8:

```sh
ld: libuv.a(libuv_la-udp.o): in function `uv__udp_sendmsg': src/unix/udp.c:367: undefined reference to ‘sendmmsg’
ld: libuv.a(libuv_la-udp.o): in function `uv__udp_io': src/unix/udp.c:186: undefined reference to ‘recvmmsg’
collect2: error: ld returned 1 exit status
```

Since we don’t use the UDP functionality of libuv, a quick hack of just commenting out these functions allows the build to link successfully and work with current 1.44.3-dev (today git) the same as it did with the last release.

This seems to be due to the removal of the `HAVE_MMSG` / `__NR_recvmmsg` / `__NR_sendmmsg` conditionals in [this commit](https://github.com/libuv/libuv/pull/3830).

I have not yet rebuilt our GCC-based SH4A and SH4A-EB uclibc-ng cross-compilers to target Linux 3.10 yet.  If Linux 3.10 is a *hard requirement*, we certainly can update our cross-compiler and test again, however, it seems it would be very little effort to fix this particular case, and it would be advantageous. 

While I do understand that Linux 2.6 support will go away *eventually*, it’s still commonly encountered on various embedded devices (routers, SBCs, etc. mostly using SH4, MIPS, ARM, PPC architectures).

Updating the Linux kernel used in the firmware of routers and other embedded devices is unfortunately non-trivial, if even possible at all. Although many of these embedded devices are old, they are long-lived and will remain in use for a long time.

Embedded and enterprise vendors still support the 2.6 kernel as well. Red Hat, for example, is supporting Enterprise Linux 6 ELS through at least June 30, 2024.

**Comment by bnoordhuis** [comment]
> it seems it would be very little effort to fix this particular case

Depends on what you mean by "fix".

There was quite a bit of support/fallback code around recvmmsg/sendmmsg (not to mention ifdefs) and I don't plan on adding that back.

Would it work for you if libuv dlsym'ed the symbols? You'll still need a definition of `struct mmsghdr` at compile time but it sounds like that wasn't an issue for you.

> Red Hat, for example, is supporting Enterprise Linux 6 ELS through at least June 30, 2024

You're referring to ELS, right? I wouldn't call that support; RedHat isn't going to fix any bugs you report.

**Comment by johnsonjh** [comment]
> You're referring to ELS, right? I wouldn't call that support; RedHat isn't going to fix any bugs you report.

Well, “*critical-impact security fixes and urgent priority bug fixes*” only, which is essentially the same as what Ubuntu ESM provides.

Linux 2.6 is also the current kernel series used for old yet still common Synology ([DS212J](https://www.synology.com/en-us/support/download/DS212j?version=6.2#system) NAS) systems running DSM 6.2.  [Golang is still supporting these systems too.](https://github.com/golang/go/issues/57333) I do understand that everyone has to draw the line for support somewhere, and the future will eventually bring other breaking changes.

> Would it work for you if libuv dlsym'ed the symbols? You'll still need a definition of `struct mmsghdr` at compile time but it sounds like that wasn't an issue for you.

That would probably work.

I think it would make the most sense to first check if this is something specific to uClibc-ng.  Right now, SH4 is our only uClibc-ng-based build, and the only place I’d seen the issue.  I’ll check that first and get back to you.

Thank you for your work on libuv.

**Comment by johnsonjh** [comment]
Just an update, from uClibc-NG source:

```
 » grep 'added' libc/sysdeps/linux/common/bits/kernel-features.h
/* On x86 another `getrlimit' syscall was added in 2.3.25.  */
/* Linux 2.3.39 sparc added setresuid.  */
/* Support for various CLOEXEC and NONBLOCK flags was added for x86,
/* Support for various CLOEXEC and NONBLOCK flags was added for x86,
/* Support for the accept4 syscall was added in 2.6.28.  */
/* Support for the accept4 syscall for alpha was added after 2.6.33-rc1.  */
/* Support for the recvmmsg/sendmmsg syscall was added in 2.6.33  */
/* Support for the FUTEX_CLOCK_REALTIME flag was added in 2.6.29.  */
/* Support for PI futexes was added in 2.6.18.  */
/* Support for private futexes was added in 2.6.22.  */
/* Support for fallocate was added in 2.6.23,
```

So, 2.6.33 is probably the “real” new minimum currently.  

The dlsym path would probably be fine here, but for now, I can also live with locally patching libuv for 2.6.32 usage.
