### ISSUE TITLE
Compilation failure on NetBSD 10.1

### ISSUE THREAD

**Issue by johnsonjh** [libuv/libuv#4785]
Current release and v1.x branch fails to compile on NetBSD 10.1_STABLE:

```
  CC       src/unix/libuv_la-core.lo
src/unix/core.c: In function 'uv_available_parallelism':
src/unix/core.c:2001:58: error: passing argument 3 of 'sched_getaffinity_np' from incompatible pointer type [-Wincompatible-pointer-types]
 2001 |     if (0 == sched_getaffinity_np(getpid(), sizeof(set), &set))
      |                                                          ^~~~
      |                                                          |
      |                                                          cpuset_t ** {aka struct _cpuset **}
In file included from /usr/include/pthread.h:38,
                 from ./include/uv/unix.h:43,
                 from ./include/uv.h:72,
                 from src/unix/core.c:21:
/usr/include/sched.h:67:45: note: expected 'cpuset_t *' {aka 'struct _cpuset *'} but argument is of type 'cpuset_t **' {aka 'struct _cpuset **'}
   67 | int     sched_getaffinity_np(pid_t, size_t, cpuset_t *);
      |                                             ^~~~~~~~~~
src/unix/core.c:2002:26: error: passing argument 1 of 'uv__cpu_count' from incompatible pointer type [-Wincompatible-pointer-types]
 2002 |       rc = uv__cpu_count(&set);
      |                          ^~~~
      |                          |
      |                          cpuset_t ** {aka struct _cpuset **}
src/unix/core.c:1954:36: note: expected 'cpuset_t *' {aka 'struct _cpuset *'} but argument is of type 'cpuset_t **' {aka 'struct _cpuset **'}
 1954 | static int uv__cpu_count(cpuset_t* set) {
      |                          ~~~~~~~~~~^~~
gmake[1]: *** [Makefile:2739: src/unix/libuv_la-core.lo] Error 1
```

Haven't had a chance to look into it much further yet.

**Comment by bnoordhuis** [comment]
That's specifically in a netbsd-only code path that was added in e1a546525 from September 2024. Presumably it worked at that time.

**Comment by santigimeno** [comment]
Possible fix: https://github.com/libuv/libuv/pull/4787

**Comment by johnsonjh** [comment]
Verified the current code failing is working on NetBSD 9 and only a problem on 10.

I have a cross-compiler for 9 and a 10 VM.  I could setup a 9 VM if needed. I can test later today.
