### ISSUE TITLE
Build failure on OpenBSD, Haiku, OpenIndiana, and Solaris 11.4 since 7b75935

### ISSUE THREAD

**Issue by johnsonjh** [libuv/libuv#4608]
The most recent commit to v1.x branch (https://github.com/libuv/libuv/commit/7b75935b00567d29ac982903e5f188ab78b4ba9b) is breaking the build on (at least) Haiku:

```c
src/unix/async.c: In function 'uv__async_send':
src/unix/async.c:231:17: error: storage size of 'ev' isn't known
  231 |   struct kevent ev;
      |                 ^~
src/unix/async.c:231:17: warning: unused variable 'ev' [-Wunused-variable]
  231 |   struct kevent ev;
      |                 ^~

src/unix/async.c:233:7: error: 'kqueue_evfilt_user_support' undeclared (first use in this function)
  233 |   if (kqueue_evfilt_user_support) {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/unix/async.c:233:7: note: each undeclared identifier is reported only once for each function it appears in

src/unix/async.c:235:5: warning: implicit declaration of function 'EV_SET'; did you mean 'FD_SET'? [-Wimplicit-function-declaration]
  235 |     EV_SET(&ev, fd, EVFILT_USER, 0, NOTE_TRIGGER, 0, 0);
      |     ^~~~~~
      |     FD_SET
src/unix/async.c:235:21: error: 'EVFILT_USER' undeclared (first use in this function)
  235 |     EV_SET(&ev, fd, EVFILT_USER, 0, NOTE_TRIGGER, 0, 0);
      |                     ^~~~~~~~~~~
src/unix/async.c:235:37: error: 'NOTE_TRIGGER' undeclared (first use in this function)
  235 |     EV_SET(&ev, fd, EVFILT_USER, 0, NOTE_TRIGGER, 0, 0);
      |                                     ^~~~~~~~~~~~

src/unix/async.c:236:9: warning: implicit declaration of function 'kevent' [-Wimplicit-function-declaration]
  236 |     r = kevent(loop->backend_fd, &ev, 1, NULL, 0, NULL);
      |         ^~~~~~
```

I know Haiku isn't officially supported, but this can probably be avoided.  I haven't had a chance to look into the fix yet myself, but should be able to later today.

**Comment by bnoordhuis** [comment]
I'd be open to testing haiku regularly if there's an easy, low maintenance way of doing it on GHA.

**Comment by bnoordhuis** [comment]
Back on topic, does haiku have kqueue? The code in async.c is activated based on whether EVFILT_USER and NOTE_TRIGGER are defined.

**Comment by johnsonjh** [comment]
Further testing shows this is also failing to compile on both Solaris 11.4 as well as current illumos/OpenIndiana with the following error, which seems to be the same problem as Haiku:

```c
src/unix/async.c: In function ‘uv__async_send’:
src/unix/async.c:231:17: error: storage size of ‘ev’ isn’t known
  231 |   struct kevent ev;                                                                                      
      |                 ^~
src/unix/async.c:233:7: error: ‘kqueue_evfilt_user_support’ undeclared (first use in this function)
  233 |   if (kqueue_evfilt_user_support) {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/unix/async.c:233:7: note: each undeclared identifier is reported only once for each function it appears in
src/unix/async.c:235:5: warning: implicit declaration of function ‘EV_SET’; did you mean ‘FD_SET’? [-Wimplicit-fu
nction-declaration]
  235 |     EV_SET(&ev, fd, EVFILT_USER, 0, NOTE_TRIGGER, 0, 0);
      |     ^~~~~~
      |     FD_SET
src/unix/async.c:235:21: error: ‘EVFILT_USER’ undeclared (first use in this function)
  235 |     EV_SET(&ev, fd, EVFILT_USER, 0, NOTE_TRIGGER, 0, 0);
      |                     ^~~~~~~~~~~
src/unix/async.c:235:37: error: ‘NOTE_TRIGGER’ undeclared (first use in this function)
  235 |     EV_SET(&ev, fd, EVFILT_USER, 0, NOTE_TRIGGER, 0, 0);
      |                                     ^~~~~~~~~~~~
src/unix/async.c:236:9: warning: implicit declaration of function ‘kevent’ [-Wimplicit-function-declaration]
  236 |     r = kevent(loop->backend_fd, &ev, 1, NULL, 0, NULL);
      |         ^~~~~~
src/unix/async.c:231:17: warning: unused variable ‘ev’ [-Wunused-variable]
  231 |   struct kevent ev;
      |                 ^~
```

**Comment by johnsonjh** [comment]
OpenBSD 7.6 is also failing, same error:

```c
src/unix/async.c:231:17: error: variable has incomplete type 'struct kevent'
  struct kevent ev;
                ^
src/unix/async.c:231:10: note: forward declaration of 'struct kevent'
  struct kevent ev;
         ^
src/unix/async.c:233:7: error: use of undeclared identifier 'kqueue_evfilt_user_support'
  if (kqueue_evfilt_user_support) {
      ^
src/unix/async.c:235:5: warning: implicit declaration of function 'EV_SET' [-Wimplicit-function-declaration]
    EV_SET(&ev, fd, EVFILT_USER, 0, NOTE_TRIGGER, 0, 0);
    ^
src/unix/async.c:235:21: error: use of undeclared identifier 'EVFILT_USER'
    EV_SET(&ev, fd, EVFILT_USER, 0, NOTE_TRIGGER, 0, 0);
                    ^
src/unix/async.c:235:37: error: use of undeclared identifier 'NOTE_TRIGGER'
    EV_SET(&ev, fd, EVFILT_USER, 0, NOTE_TRIGGER, 0, 0);
                                    ^
src/unix/async.c:236:9: warning: implicit declaration of function 'kevent' [-Wimplicit-function-declaration]
    r = kevent(loop->backend_fd, &ev, 1, NULL, 0, NULL);
        ^
2 warnings and 4 errors generated.

```

A quick look on OpenBSD, Solaris, illumos, and Haiku indicates that I actually don't have any defintion of `EVFILT_USER` nor `NOTE_TRIGGER` anywhere in any headers.

I see them *only* on NetBSD and FreeBSD.

**Comment by johnsonjh** [comment]
I should add these are all built using the configure script.

I do not have cmake installed on any of these systems to test at this time.

**Comment by bnoordhuis** [comment]
#4612 should (hopefully) fix the breakage.

**Comment by johnsonjh** [comment]
@bnoordhuis 

Testing current v1.x branch on Haiku, OpenBSD, and Solaris 11.4 with the https://github.com/bnoordhuis/libuv/commit/45c76913235cd4670174d099dc1fb68ec727d0e6 commit applied, it is still not compiling, giving exactly the same error:

<details>

```c
src/unix/async.c: In function ‘uv__async_send’:
src/unix/async.c:235:17: error: storage size of ‘ev’ isn’t known
  235 |   struct kevent ev;
      |                 ^~
src/unix/async.c:237:7: error: ‘kqueue_evfilt_user_support’ undeclared (first use in this function)
  237 |   if (kqueue_evfilt_user_support) {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/unix/async.c:237:7: note: each undeclared identifier is reported only once for each function it appears in
src/unix/async.c:239:5: warning: implicit declaration of function ‘EV_SET’; did you mean ‘FD_SET’? [-Wimplicit-function-declaration]
  239 |     EV_SET(&ev, fd, EVFILT_USER, 0, NOTE_TRIGGER, 0, 0);
      |     ^~~~~~
      |     FD_SET
src/unix/async.c:239:21: error: ‘EVFILT_USER’ undeclared (first use in this function)
  239 |     EV_SET(&ev, fd, EVFILT_USER, 0, NOTE_TRIGGER, 0, 0);
      |                     ^~~~~~~~~~~
src/unix/async.c:239:37: error: ‘NOTE_TRIGGER’ undeclared (first use in this function)
  239 |     EV_SET(&ev, fd, EVFILT_USER, 0, NOTE_TRIGGER, 0, 0);
      |                                     ^~~~~~~~~~~~
src/unix/async.c:240:9: warning: implicit declaration of function ‘kevent’ [-Wimplicit-function-declaration]
  240 |     r = kevent(loop->backend_fd, &ev, 1, NULL, 0, NULL);
      |         ^~~~~~
src/unix/async.c:235:17: warning: unused variable ‘ev’ [-Wunused-variable]
  235 |   struct kevent ev;
      |                 ^~
```

</details>

**Comment by johnsonjh** [comment]
@bnoordhuis 

I finally had time to actually look at the problem.

`UV__KQUEUE_EVFILT_USER` is defined to 0, but the code that is checking to see if it usable only check if it is defined and not the value, so it is always used unconditionally.

However, this still seems like it's overzealous.  The check in `unix/internal.h` only checks the OS from what I can see, it doesn't actually ever look for the existence of EVFILT_USER and NOTE_TRIGGER, and this will also cause a compilation failure on older systems.

I think a proper fix is just the following applied to `v1.x`:

```diff
diff --git a/src/unix/async.c b/src/unix/async.c
index aef25f6b..8265a43a 100644
--- a/src/unix/async.c
+++ b/src/unix/async.c
@@ -220,21 +220,21 @@ static void uv__async_send(uv_loop_t* loop) {
   len = 1;
   fd = loop->async_wfd;
 
 #if defined(__linux__)
   if (fd == -1) {
     static const uint64_t val = 1;
     buf = &val;
     len = sizeof(val);
     fd = loop->async_io_watcher.fd;  /* eventfd */
   }
-#elif defined(UV__KQUEUE_EVFILT_USER)
+#elif UV__KQUEUE_EVFILT_USER
   struct kevent ev;
 
   if (kqueue_evfilt_user_support) {
     fd = loop->async_io_watcher.fd; /* magic number for EVFILT_USER */
     EV_SET(&ev, fd, EVFILT_USER, 0, NOTE_TRIGGER, 0, 0);
     r = kevent(loop->backend_fd, &ev, 1, NULL, 0, NULL);
     if (r == 0)
       return;
     abort();
   }
```

**Comment by johnsonjh** [comment]
See https://github.com/libuv/libuv/pull/4618

**Comment by bnoordhuis** [comment]
Fixed by #4618.
