### ISSUE TITLE
compilation failed - make failed on MinGW64

### ISSUE THREAD

**Issue by SzAmmi** [libuv/libuv#1194]
I've installed MSYS2 and downloaded MINGW64 using `pacman`. I want to compile `libuv`, but I'm always getting `error: 'ERROR_ELEVATION_REQUIRED' undeclared` while running `make`. I use MINGW64.

```
$ make
...
...
src/win/error.c: In function 'uv_fatal_error':
src/win/error.c:61:20: warning: overflow in implicit constant conversion [-Woverflow]
   *((char*)NULL) = 0xff; /* Force debug break */
                    ^~~~
src/win/error.c: In function 'uv_translate_sys_error':
src/win/error.c:74:10: error: 'ERROR_ELEVATION_REQUIRED' undeclared (first use in this function)
     case ERROR_ELEVATION_REQUIRED:          return UV_EACCES;
          ^~~~~~~~~~~~~~~~~~~~~~~~
src/win/error.c:74:10: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:1801: src/win/libuv_la-error.lo] Error 1
```

How can I fix it?

**Comment by bnoordhuis** [comment]
What version of mingw64 is that?  FWIW, `ERROR_ELEVATION_REQUIRED` was introduced in commit 11ce5df.  An older commit should still work.

/cc @richardlau

**Comment by SzAmmi** [comment]
@bnoordhuis The latest I think - I downloaded it today - 3h ago. I discovered that `ERROR_ELEVATION_REQUIRED` is missing in `C:\msys64\mingw64\x86_64-w64-mingw32\include\winerror.h`. I've all mingw-w64 tools:

```
mingw-w64-x86_64-binutils 2.27-2
mingw-w64-x86_64-bzip2 1.0.6-6
mingw-w64-x86_64-ca-certificates 20150426-2
mingw-w64-x86_64-crt-git 5.0.0.4762.ea6e207-1
mingw-w64-x86_64-expat 2.2.0-2
mingw-w64-x86_64-gcc 6.3.0-1
mingw-w64-x86_64-gcc-ada 6.3.0-1
mingw-w64-x86_64-gcc-fortran 6.3.0-1
mingw-w64-x86_64-gcc-libgfortran 6.3.0-1
mingw-w64-x86_64-gcc-libs 6.3.0-1
mingw-w64-x86_64-gcc-objc 6.3.0-1
mingw-w64-x86_64-gdb 7.12-2
mingw-w64-x86_64-gdbm 1.12-1
mingw-w64-x86_64-gettext 0.19.7-1
mingw-w64-x86_64-gmp 6.1.2-1
mingw-w64-x86_64-headers-git 5.0.0.4764.0dae3f1-1
mingw-w64-x86_64-isl 0.17.1-1
mingw-w64-x86_64-libffi 3.2.1-4
mingw-w64-x86_64-libiconv 1.14-5
mingw-w64-x86_64-libmangle-git 5.0.0.4760.d3089b5-1
mingw-w64-x86_64-libsystre 1.0.1-2
mingw-w64-x86_64-libtasn1 4.9-1
mingw-w64-x86_64-libtre-git r122.c2f5d13-4
mingw-w64-x86_64-libwinpthread-git 5.0.0.4761.02bea78-1
mingw-w64-x86_64-make 4.1.2351.a80a8b8-1
mingw-w64-x86_64-mpc 1.0.3-2
mingw-w64-x86_64-mpfr 3.1.5.p1-1
mingw-w64-x86_64-ncurses 6.0.20161105-1
mingw-w64-x86_64-openssl 1.0.2.j-1
mingw-w64-x86_64-p11-kit 0.23.2-2
mingw-w64-x86_64-pkg-config 0.29.1-2
mingw-w64-x86_64-python2 2.7.12-3
mingw-w64-x86_64-readline 7.0.001-1
mingw-w64-x86_64-tcl 8.6.6-1
mingw-w64-x86_64-termcap 1.3.1-2
mingw-w64-x86_64-tk 8.6.6-1
mingw-w64-x86_64-tools-git 5.0.0.4760.d3089b5-1
mingw-w64-x86_64-windows-default-manifest 6.4-3
mingw-w64-x86_64-winpthreads-git 5.0.0.4761.02bea78-1
mingw-w64-x86_64-winstorecompat-git 5.0.0.4760.d3089b5-1
mingw-w64-x86_64-zlib 1.2.8-10
```

**Comment by SzAmmi** [comment]
All my packages I've installed and their versions:
```
$ pacman -Q
autoconf 2.69-3
automake-wrapper 10-1
automake1.10 1.10.3-3
automake1.11 1.11.6-3
automake1.12 1.12.6-3
automake1.13 1.13.4-4
automake1.14 1.14.1-3
automake1.15 1.15-2
automake1.6 1.6.3-2
automake1.7 1.7.9-2
automake1.8 1.8.5-3
automake1.9 1.9.6-2
bash 4.3.046-1
bash-completion 2.3-1
binutils 2.25.1-2
bsdcpio 3.2.2-2
bsdtar 3.2.2-2
bzip2 1.0.6-2
ca-certificates 20150426-1
catgets 1.1-2
clang-svn 60106.1d5b05f-1
cmake 3.6.2-1
coreutils 8.25-1
crypt 1.3-1
curl 7.51.0-1
dash 0.5.9.1-1
db 5.3.28-2
diffutils 3.5-1
expat 2.2.0-2
file 5.29-1
filesystem 2016.07-2
findutils 4.6.0-1
flex 2.6.1-1
gawk 4.1.4-1
gcc 5.3.0-3
gcc-libs 5.3.0-3
gdb 7.9-2
gdbm 1.11-3
gettext 0.19.7-3
git 2.10.2-1
glib2 2.48.0-1
gmp 6.1.0-2
gnupg 1.4.21-1
grep 2.26-1
gyp-git r2097.691cecc-1
gzip 1.8-1
heimdal 1.5.3-9
heimdal-libs 1.5.3-9
icu 56.1-1
inetutils 1.9.2-1
info 6.1-1
isl 0.16.1-1
less 481-1
libarchive 3.2.2-2
libasprintf 0.19.7-3
libassuan 2.4.2-1
libbz2 1.0.6-2
libcatgets 1.1-2
libcrypt 1.3-1
libcurl 7.51.0-1
libdb 5.3.28-2
libedit 3.1-20150325
libexpat 2.2.0-2
libffi 3.2.1-1
libgcrypt 1.6.4-1
libgdbm 1.11-3
libgettextpo 0.19.7-3
libgpg-error 1.25-1
libgpgme 1.6.0-1
libiconv 1.14-2
libidn 1.33-1
libintl 0.19.7-3
libltdl 2.4.6-2
liblzma 5.2.2-1
liblzo2 2.09-1
libmetalink 0.1.2-2
libnettle 3.3-1
libopenssl 1.0.2.j-1
libp11-kit 0.23.2-1
libpcre 8.38-1
libpcre16 8.38-1
libpcre32 8.38-1
libpcrecpp 8.38-1
libpcreposix 8.38-1
libreadline 6.3.008-7
libsqlite 3.10.0.0-1
libssh2 1.7.0-1
libtasn1 4.9-1
libtool 2.4.6-2
libutil-linux 2.26.2-1
libxml2 2.9.2-2
libxslt 1.1.28-7
llvm-svn 124592.2aebced-1
lndir 1.0.3-1
m4 1.4.17-4
make 4.2.1-1
mingw-w64-x86_64-binutils 2.27-2
mingw-w64-x86_64-bzip2 1.0.6-6
mingw-w64-x86_64-ca-certificates 20150426-2
mingw-w64-x86_64-crt-git 5.0.0.4762.ea6e207-1
mingw-w64-x86_64-expat 2.2.0-2
mingw-w64-x86_64-gcc 6.3.0-1
mingw-w64-x86_64-gcc-ada 6.3.0-1
mingw-w64-x86_64-gcc-fortran 6.3.0-1
mingw-w64-x86_64-gcc-libgfortran 6.3.0-1
mingw-w64-x86_64-gcc-libs 6.3.0-1
mingw-w64-x86_64-gcc-objc 6.3.0-1
mingw-w64-x86_64-gdb 7.12-2
mingw-w64-x86_64-gdbm 1.12-1
mingw-w64-x86_64-gettext 0.19.7-1
mingw-w64-x86_64-gmp 6.1.2-1
mingw-w64-x86_64-headers-git 5.0.0.4764.0dae3f1-1
mingw-w64-x86_64-isl 0.17.1-1
mingw-w64-x86_64-libffi 3.2.1-4
mingw-w64-x86_64-libiconv 1.14-5
mingw-w64-x86_64-libmangle-git 5.0.0.4760.d3089b5-1
mingw-w64-x86_64-libsystre 1.0.1-2
mingw-w64-x86_64-libtasn1 4.9-1
mingw-w64-x86_64-libtre-git r122.c2f5d13-4
mingw-w64-x86_64-libwinpthread-git 5.0.0.4761.02bea78-1
mingw-w64-x86_64-make 4.1.2351.a80a8b8-1
mingw-w64-x86_64-mpc 1.0.3-2
mingw-w64-x86_64-mpfr 3.1.5.p1-1
mingw-w64-x86_64-ncurses 6.0.20161105-1
mingw-w64-x86_64-openssl 1.0.2.j-1
mingw-w64-x86_64-p11-kit 0.23.2-2
mingw-w64-x86_64-pkg-config 0.29.1-2
mingw-w64-x86_64-python2 2.7.12-3
mingw-w64-x86_64-readline 7.0.001-1
mingw-w64-x86_64-tcl 8.6.6-1
mingw-w64-x86_64-termcap 1.3.1-2
mingw-w64-x86_64-tk 8.6.6-1
mingw-w64-x86_64-tools-git 5.0.0.4760.d3089b5-1
mingw-w64-x86_64-windows-default-manifest 6.4-3
mingw-w64-x86_64-winpthreads-git 5.0.0.4761.02bea78-1
mingw-w64-x86_64-winstorecompat-git 5.0.0.4760.d3089b5-1
mingw-w64-x86_64-zlib 1.2.8-10
mintty 1~2.6.2-1
mpc 1.0.3-1
mpfr 3.1.4-1
msys2-keyring r9.397a52e-1
msys2-launcher-git 0.3.32.56c2ba7-2
msys2-runtime 2.6.0-1
msys2-runtime-devel 2.6.0-1
msys2-w32api-headers 5.0.0.4732.6172d2f-1
msys2-w32api-runtime 5.0.0.4732.6172d2f-1
nano 2.7.1-1
ncurses 6.0.20161112-1
openssh 7.3p1-2
openssl 1.0.2.j-1
p11-kit 0.23.2-1
pacman 5.0.1-1
pacman-mirrors 20160112-1
pactoys-git r2.07ca37f-1
pax-git 20140703.2.1.g469552a-1
pcre 8.38-1
perl 5.22.1-1
perl-Authen-SASL 2.16-2
perl-Convert-BinHex 1.123-2
perl-Encode-Locale 1.04-1
perl-Error 0.17024-1
perl-File-Listing 6.04-2
perl-HTML-Parser 3.71-3
perl-HTML-Tagset 3.20-2
perl-HTTP-Cookies 6.01-2
perl-HTTP-Daemon 6.01-2
perl-HTTP-Date 6.02-2
perl-HTTP-Message 6.06-2
perl-HTTP-Negotiate 6.01-2
perl-IO-Socket-SSL 2.016-1
perl-IO-stringy 2.111-1
perl-LWP-MediaTypes 6.02-2
perl-MIME-tools 5.506-1
perl-MailTools 2.14-1
perl-Net-HTTP 6.09-1
perl-Net-SMTP-SSL 1.02-1
perl-Net-SSLeay 1.72-1
perl-TermReadKey 2.33-1
perl-TimeDate 2.30-2
perl-URI 1.68-1
perl-WWW-RobotRules 6.02-2
perl-libwww 6.13-1
pkg-config 0.29.1-1
pkgfile 15-1
python2 2.7.11-1
python2-setuptools 20.2.2-1
rebase 4.4.2-1
sed 4.2.2-2
tar 1.29-1
tftp-hpa 5.2-1
time 1.7-1
ttyrec 1.0.8-1
tzcode 2015.e-1
util-linux 2.26.2-1
vim 8.0.0124-1
wget 1.18-1
which 2.21-2
windows-default-manifest 6.4-1
xz 5.2.2-1
zlib 1.2.8-3
```

**Comment by SzAmmi** [comment]
It looks like some error definitions in MinGW64's win32api are missing. While compiling @richardlau's fork I got this:
```
  CCLD     libuv.la
src/.libs/libuv_la-fs-poll.o: In function `timer_cb':
/c/libuv-1.x/src/fs-poll.c:163: undefined reference to `__assert_func'
/c/libuv-1.x/src/fs-poll.c:164: undefined reference to `__assert_func'
src/.libs/libuv_la-fs-poll.o: In function `uv_fs_poll_stop':
/c/libuv-1.x/src/fs-poll.c:111: undefined reference to `__assert_func'
/c/libuv-1.x/src/fs-poll.c:112: undefined reference to `__assert_func'
src/.libs/libuv_la-fs-poll.o: In function `uv_fs_poll_getpath':
/c/libuv-1.x/src/fs-poll.c:138: undefined reference to `__assert_func'
src/.libs/libuv_la-threadpool.o:/c/libuv-1.x/src/threadpool.c:252: more undefined references to `__assert_func' follow
src/.libs/libuv_la-uv-common.o: In function `uv(float, long double,...)(...)':
/c/libuv-1.x/src/uv-common.c:84: undefined reference to `__errno'
/c/libuv-1.x/src/uv-common.c:86: undefined reference to `__errno'
src/.libs/libuv_la-uv-common.o: In function `uv_loop_delete':
/c/libuv-1.x/src/uv-common.c:651: undefined reference to `__assert_func'
src/win/.libs/libuv_la-core.o: In function `uv_process_endgames':
C:\libuv-1.x/src/win/handle-inl.h:155: undefined reference to `uv__fs_poll_endgame'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:1210: libuv.la] Error 1
```

**Comment by richardlau** [comment]
If MINGW64 is missing [`ERROR_ELEVATION_REQUIRED`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681388%28v=vs.85%29.aspx) then we could do 
```c++
#ifndef ERROR_ELEVATION_REQUIRED
#  define ERROR_ELEVATION_REQUIRED 740
#endif
```
Looks like `src/win/winapi.h` is the place to put this in libuv? I'll submit a PR.

**Comment by SzAmmi** [comment]
Tried to compille commit [c02176a](https://github.com/libuv/libuv/tree/c02176a23062fbde2273579ee641aa47f35d6778):
failed on `make check`:
```
$ make check
...
...
not ok 210 - spawn_reads_child_path
# exit code 3
# Output from process `spawn_reads_child_path`:
# exit_cb
# Assertion failed in test/test-spawn.c on line 68: exit_status == 1
#
# This application has requested the Runtime to terminate it in an unusual way.
# Please contact the application's support team for more information.
...
...
FAIL: test/run-tests.exe
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [Makefile:4190: check-TESTS] Error 1
make[1]: Leaving directory '/c/libuv-c02176a23062fbde2273579ee641aa47f35d6778'
make: *** [Makefile:4447: check-am] Error 2
```

**Comment by SzAmmi** [comment]
@richardlau 

Your commit doesn't change anything:
```
src/win/error.c: In function 'uv_fatal_error':
src/win/error.c:61:20: warning: overflow in implicit constant conversion [-Woverflow]
   *((char*)NULL) = 0xff; /* Force debug break */
                    ^~~~
src/win/error.c: In function 'uv_translate_sys_error':
src/win/error.c:74:10: error: 'ERROR_ELEVATION_REQUIRED' undeclared (first use in this function)
     case ERROR_ELEVATION_REQUIRED:          return UV_EACCES;
          ^~~~~~~~~~~~~~~~~~~~~~~~
src/win/error.c:74:10: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:1801: src/win/libuv_la-error.lo] Error 1
```

Please notice, if I add:
```
#ifndef ERROR_ELEVATION_REQUIRED
#  define ERROR_ELEVATION_REQUIRED 740
#endif
```
to mingw64's `winerror.h`: `C:\msys64\mingw64\x86_64-w64-mingw32\include\winerror.h`; `make` is all OK but `make check` gives me this:
```
$ make check
...
not ok 210 - spawn_reads_child_path
# exit code 3
# Output from process `spawn_reads_child_path`:
# exit_cb
# Assertion failed in test/test-spawn.c on line 68: exit_status == 1
#
# This application has requested the Runtime to terminate it in an unusual way.
# Please contact the application's support team for more information.
...
ok 289 - queue_foreach_delete
FAIL: test/run-tests.exe
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [Makefile:4190: check-TESTS] Error 1
make[1]: Leaving directory '/c/libuv-11ce5df5eadd67fa951b8c4c6293fa784d21cf80'
make: *** [Makefile:4447: check-am] Error 2
```

I'm on Windows 8 (not 8.1).

**Comment by SzAmmi** [comment]
Working! Thanks!

**Comment by SzAmmi** [comment]
Failed to do make check. Same error with ERROR_ELEVATION_REQUIRED in assert. Tomorrow I'll post the error message.

**Comment by SzAmmi** [comment]
@richardlau `make check` failed. Please see:

```
In file included from test/test-error.c:23:0:
test/test-error.c: In function 'run_test_sys_error':
test/test-error.c:56:33: error: 'ERROR_ELEVATION_REQUIRED' undeclared (first use in this function)
   ASSERT(uv_translate_sys_error(ERROR_ELEVATION_REQUIRED) == UV_EACCES);
                                 ^
test/task.h:98:9: note: in definition of macro 'ASSERT'
   if (!(expr)) {                                          \
         ^~~~
test/test-error.c:56:33: note: each undeclared identifier is reported only once for each function it appears in
   ASSERT(uv_translate_sys_error(ERROR_ELEVATION_REQUIRED) == UV_EACCES);
                                 ^
test/task.h:98:9: note: in definition of macro 'ASSERT'
   if (!(expr)) {                                          \
         ^~~~
make[1]: *** [Makefile:2508: test/test_run_tests-test-error.o] Error 1
make[1]: Leaving directory '/c/libuv-95bbbeea3c1f8bac97adc021bc37f9daf3b8cac4'
make: *** [Makefile:4446: check-am] Error 2
```

**Comment by SzAmmi** [comment]
Adding
```
#include <win/winapi.h>
```
to `test-error.c` can fix this - already tried.

**Comment by SzAmmi** [comment]
Hello? Is anybody here?

**Comment by saghul** [comment]
The include shouldn't be needed there.  Maybe inside the windows code which defines the mapping.

**Comment by SzAmmi** [comment]
@saghul Yeah, you're right. We can check if someone is using Windows.

**Comment by SzAmmi** [comment]
I'm closing this issue. Problem with `make` solved. Now I've another fail with `make check`, see #1200
