### ISSUE TITLE
libuv broken on Solaris, Cygwin, HP-UX, and Haiku due to pwritev/preadv use

### ISSUE THREAD

**Issue by johnsonjh** [libuv/libuv#4176]
libuv (v1.x branch, as of 2023-10-21) fails to link on Cygwin due to missing pwritev/preadv functions.

```sh
x86_64-pc-cygwin-ld: libuv.a(libuv_la-fs.o): in function `uv__fs_write_do':
src/unix/fs.c:1101: undefined reference to `pwritev'
x86_64-pc-cygwin-ld: libuv.a(libuv_la-fs.o): in function `uv__fs_read_do':
src/unix/fs.c:418: undefined reference to `preadv'
```

**Comment by johnsonjh** [comment]
I'll close this for now - it seems to be a problem with the CI build system here being served a stale archive from GitHub.  I'll re-open once I rule that out, if it's still a problem.

**Comment by johnsonjh** [comment]
Nope, I can confirm that libuv is now broken on Cygwin.

Also, Solaris doesn't have this function, which seems to be some kind of non-standard extension... AIX does have it, but it's noted as being non-standard.

git bisect shows fef619608bda33a7cb37e78f08ee8abbb62458a3 is the first bad commit.

**Comment by johnsonjh** [comment]
HP-UX is also affected by this.  Also less of a concern, since it's only supported (and a maintenance burden) through 12/25, though some usage will likely continue through 2026.

**Comment by bnoordhuis** [comment]
> since we're going to be supporting Solaris through at least 2034

You maybe. We won't. :-)

All three platforms are self-serve, meaning great if it works for you, send pull requests if it doesn't.

Having said that, I removed all the fallback code deliberately and I don't really want to reintroduce it for platforms I don't care about. Keeping that kind of spaghetti code around takes time away from more worthy endeavors.

I suppose that, if you're using libuv commercially, we can maybe come to some kind of business arrangement?

**Comment by johnsonjh** [comment]
This also breaks MacOS 11 (11.7.10 was released on 9/11/2023, and is still a supported release).

> I suppose that, if you're using libuv commercially, we can maybe come to some kind of business arrangement?

Perhaps, but it's more likely going to end up just more work for me, for now.

**Comment by johnsonjh** [comment]
I can respect the decision if it's made, but it's a bit disappointing.  We usually target systems in terms of a C standard (usually C11) and POSIX conformance (usually POSIX.1-2008), but these new functions that are being required are not a part of POSIX nor any other standard, so having a POSIX-confirming system is no longer sufficient for libuv.

And wasn't the motto for the project (once) 'we ifdef so you don't have to'?

But, I do understand your side.  I guess my consulting rates will have to go up :)

**Comment by bnoordhuis** [comment]
Well, let me think about it. The decision would have been different for me if those platforms had decent user bases.

Somewhat to my surprise cygwin's cmake package (which uses libuv) is fairly recent so I guess there are at least _some_ users still out there.

**Comment by bnoordhuis** [comment]
#4178 - let's see how other maintainers feel

**Comment by johnsonjh** [comment]
I guess it could be done via a runtime check and weak symbols.
