### ISSUE TITLE
make failed at aarch64-linux-android arm64

### ISSUE THREAD

**Issue by fusuiyi123** [libuv/libuv#2768]
* **Version**: 1.35.0
* **Platform**:  `Linux 951ba020b0df 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 GNU/Linux`
NDK=r18
API=28
ARCH="arm64"
```
./autogen.sh
./configure --host=aarch64-linux-android CXX=/opt/toolchain/bin/aarch64-linux-android-clang++ CXXLD=/opt/toolchain/bin/aarch64-linux-android-clang++ CC=/opt/toolchain/bin/aarch64-linux-android-clang CCLD=/opt/toolchain/bin/aarch64-linux-android-clang AR=/opt/toolchain/bin/aarch64-linux-android-ar RANLIB=/opt/toolchain/bin/aarch64-linux-android-ranlib CXXFLAGS="-fvisibility=hidden" CFLAGS="-fvisibility=hidden" LDFLAGS="" --with-pic --enable-static
root@951ba020b0df:~/libuv-1.35.0# make
  CC       src/libuv_la-fs-poll.lo
  CC       src/libuv_la-idna.lo
  CC       src/libuv_la-inet.lo
  CC       src/libuv_la-random.lo
  CC       src/libuv_la-strscpy.lo
  CC       src/libuv_la-threadpool.lo
  CC       src/libuv_la-timer.lo
  CC       src/libuv_la-uv-data-getter-setters.lo
  CC       src/libuv_la-uv-common.lo
  CC       src/libuv_la-version.lo
  CC       src/unix/libuv_la-async.lo
  CC       src/unix/libuv_la-core.lo
  CC       src/unix/libuv_la-dl.lo
  CC       src/unix/libuv_la-fs.lo
  CC       src/unix/libuv_la-getaddrinfo.lo
  CC       src/unix/libuv_la-getnameinfo.lo
  CC       src/unix/libuv_la-loop-watcher.lo
  CC       src/unix/libuv_la-loop.lo
  CC       src/unix/libuv_la-pipe.lo
  CC       src/unix/libuv_la-poll.lo
  CC       src/unix/libuv_la-process.lo
  CC       src/unix/libuv_la-random-devurandom.lo
  CC       src/unix/libuv_la-signal.lo
  CC       src/unix/libuv_la-stream.lo
  CC       src/unix/libuv_la-tcp.lo
  CC       src/unix/libuv_la-thread.lo
  CC       src/unix/libuv_la-tty.lo
  CC       src/unix/libuv_la-udp.lo
  CC       src/unix/libuv_la-android-ifaddrs.lo
  CC       src/unix/libuv_la-linux-core.lo
  CC       src/unix/libuv_la-linux-inotify.lo
  CC       src/unix/libuv_la-linux-syscalls.lo
  CC       src/unix/libuv_la-procfs-exepath.lo
  CC       src/unix/libuv_la-pthread-fixes.lo
  CC       src/unix/libuv_la-random-getrandom.lo
  CC       src/unix/libuv_la-random-sysctl-linux.lo
  CC       src/unix/libuv_la-sysinfo-loadavg.lo
  CC       src/unix/libuv_la-proctitle.lo
  CCLD     libuv.la
src/unix/.libs/libuv_la-linux-core.o: In function `uv__hrtime':
/root/libuv-1.35.0/src/unix/linux-core.c:473: multiple definition of `uv__hrtime'
src/unix/.libs/libuv_la-linux-core.o:/root/libuv-1.35.0/src/unix/linux-core.c:473: first defined here
src/unix/.libs/libuv_la-linux-core.o: In function `uv__io_check_fd':
/root/libuv-1.35.0/src/unix/linux-core.c:180: multiple definition of `uv__io_check_fd'
src/unix/.libs/libuv_la-linux-core.o:/root/libuv-1.35.0/src/unix/linux-core.c:180: first defined here
src/unix/.libs/libuv_la-linux-core.o: In function `uv__io_fork':
/root/libuv-1.35.0/src/unix/linux-core.c:121: multiple definition of `uv__io_fork'
src/unix/.libs/libuv_la-linux-core.o:/root/libuv-1.35.0/src/unix/linux-core.c:121: first defined here
src/unix/.libs/libuv_la-linux-core.o: In function `uv__io_poll':
/root/libuv-1.35.0/src/unix/linux-core.c:201: multiple definition of `uv__io_poll'
src/unix/.libs/libuv_la-linux-core.o:/root/libuv-1.35.0/src/unix/linux-core.c:201: first defined here
src/unix/.libs/libuv_la-linux-core.o: In function `uv__platform_invalidate_fd':
/root/libuv-1.35.0/src/unix/linux-core.c:147: multiple definition of `uv__platform_invalidate_fd'
src/unix/.libs/libuv_la-linux-core.o:/root/libuv-1.35.0/src/unix/linux-core.c:147: first defined here
src/unix/.libs/libuv_la-linux-core.o: In function `uv__platform_loop_delete':
/root/libuv-1.35.0/src/unix/linux-core.c:139: multiple definition of `uv__platform_loop_delete'
src/unix/.libs/libuv_la-linux-core.o:/root/libuv-1.35.0/src/unix/linux-core.c:139: first defined here
src/unix/.libs/libuv_la-linux-core.o: In function `uv__platform_loop_init':
/root/libuv-1.35.0/src/unix/linux-core.c:86: multiple definition of `uv__platform_loop_init'
src/unix/.libs/libuv_la-linux-core.o:/root/libuv-1.35.0/src/unix/linux-core.c:86: first defined here
src/unix/.libs/libuv_la-linux-core.o: In function `uv__set_process_title':
/root/libuv-1.35.0/src/unix/linux-core.c:976: multiple definition of `uv__set_process_title'
src/unix/.libs/libuv_la-linux-core.o:/root/libuv-1.35.0/src/unix/linux-core.c:976: first defined here
src/unix/.libs/libuv_la-linux-core.o: In function `uv_cpu_info':
/root/libuv-1.35.0/src/unix/linux-core.c:610: multiple definition of `uv_cpu_info'
src/unix/.libs/libuv_la-linux-core.o:/root/libuv-1.35.0/src/unix/linux-core.c:610: first defined here
src/unix/.libs/libuv_la-linux-core.o: In function `uv_free_interface_addresses':
/root/libuv-1.35.0/src/unix/linux-core.c:965: multiple definition of `uv_free_interface_addresses'
src/unix/.libs/libuv_la-linux-core.o:/root/libuv-1.35.0/src/unix/linux-core.c:965: first defined here
src/unix/.libs/libuv_la-linux-core.o: In function `uv_get_constrained_memory':
/root/libuv-1.35.0/src/unix/linux-core.c:1084: multiple definition of `uv_get_constrained_memory'
src/unix/.libs/libuv_la-linux-core.o:/root/libuv-1.35.0/src/unix/linux-core.c:1084: first defined here
src/unix/.libs/libuv_la-linux-core.o: In function `uv_get_free_memory':
/root/libuv-1.35.0/src/unix/linux-core.c:1023: multiple definition of `uv_get_free_memory'
src/unix/.libs/libuv_la-linux-core.o:/root/libuv-1.35.0/src/unix/linux-core.c:1023: first defined here
src/unix/.libs/libuv_la-linux-core.o: In function `uv_get_total_memory':
/root/libuv-1.35.0/src/unix/linux-core.c:1039: multiple definition of `uv_get_total_memory'
src/unix/.libs/libuv_la-linux-core.o:/root/libuv-1.35.0/src/unix/linux-core.c:1039: first defined here
src/unix/.libs/libuv_la-linux-core.o: In function `uv_interface_addresses':
/root/libuv-1.35.0/src/unix/linux-core.c:876: multiple definition of `uv_interface_addresses'
src/unix/.libs/libuv_la-linux-core.o:/root/libuv-1.35.0/src/unix/linux-core.c:876: first defined here
src/unix/.libs/libuv_la-linux-core.o: In function `uv_resident_set_memory':
/root/libuv-1.35.0/src/unix/linux-core.c:506: multiple definition of `uv_resident_set_memory'
src/unix/.libs/libuv_la-linux-core.o:/root/libuv-1.35.0/src/unix/linux-core.c:506: first defined here
src/unix/.libs/libuv_la-linux-core.o: In function `uv_uptime':
/root/libuv-1.35.0/src/unix/linux-core.c:563: multiple definition of `uv_uptime'
src/unix/.libs/libuv_la-linux-core.o:/root/libuv-1.35.0/src/unix/linux-core.c:563: first defined here
src/unix/.libs/libuv_la-linux-inotify.o: In function `uv__fs_event_close':
/root/libuv-1.35.0/src/unix/linux-inotify.c:325: multiple definition of `uv__fs_event_close'
src/unix/.libs/libuv_la-linux-inotify.o:/root/libuv-1.35.0/src/unix/linux-inotify.c:325: first defined here
src/unix/.libs/libuv_la-linux-inotify.o: In function `uv__inotify_fork':
/root/libuv-1.35.0/src/unix/linux-inotify.c:86: multiple definition of `uv__inotify_fork'
src/unix/.libs/libuv_la-linux-inotify.o:/root/libuv-1.35.0/src/unix/linux-inotify.c:86: first defined here
src/unix/.libs/libuv_la-linux-inotify.o: In function `uv_fs_event_init':
/root/libuv-1.35.0/src/unix/linux-inotify.c:243: multiple definition of `uv_fs_event_init'
src/unix/.libs/libuv_la-linux-inotify.o:/root/libuv-1.35.0/src/unix/linux-inotify.c:243: first defined here
src/unix/.libs/libuv_la-linux-inotify.o: In function `uv_fs_event_start':
/root/libuv-1.35.0/src/unix/linux-inotify.c:252: multiple definition of `uv_fs_event_start'
src/unix/.libs/libuv_la-linux-inotify.o:/root/libuv-1.35.0/src/unix/linux-inotify.c:252: first defined here
src/unix/.libs/libuv_la-linux-inotify.o: In function `uv_fs_event_stop':
/root/libuv-1.35.0/src/unix/linux-inotify.c:305: multiple definition of `uv_fs_event_stop'
src/unix/.libs/libuv_la-linux-inotify.o:/root/libuv-1.35.0/src/unix/linux-inotify.c:305: first defined here
src/unix/.libs/libuv_la-linux-syscalls.o: In function `uv__dup3':
/root/libuv-1.35.0/src/unix/linux-syscalls.c:174: multiple definition of `uv__dup3'
src/unix/.libs/libuv_la-linux-syscalls.o:/root/libuv-1.35.0/src/unix/linux-syscalls.c:174: first defined here
src/unix/.libs/libuv_la-linux-syscalls.o: In function `uv__getrandom':
/root/libuv-1.35.0/src/unix/linux-syscalls.c:199: multiple definition of `uv__getrandom'
src/unix/.libs/libuv_la-linux-syscalls.o:/root/libuv-1.35.0/src/unix/linux-syscalls.c:199: first defined here
src/unix/.libs/libuv_la-linux-syscalls.o: In function `uv__preadv':
/root/libuv-1.35.0/src/unix/linux-syscalls.c:156: multiple definition of `uv__preadv'
src/unix/.libs/libuv_la-linux-syscalls.o:/root/libuv-1.35.0/src/unix/linux-syscalls.c:156: first defined here
src/unix/.libs/libuv_la-linux-syscalls.o: In function `uv__pwritev':
/root/libuv-1.35.0/src/unix/linux-syscalls.c:165: multiple definition of `uv__pwritev'
src/unix/.libs/libuv_la-linux-syscalls.o:/root/libuv-1.35.0/src/unix/linux-syscalls.c:165: first defined here
src/unix/.libs/libuv_la-linux-syscalls.o: In function `uv__recvmmsg':
/root/libuv-1.35.0/src/unix/linux-syscalls.c:147: multiple definition of `uv__recvmmsg'
src/unix/.libs/libuv_la-linux-syscalls.o:/root/libuv-1.35.0/src/unix/linux-syscalls.c:147: first defined here
src/unix/.libs/libuv_la-linux-syscalls.o: In function `uv__sendmmsg':
/root/libuv-1.35.0/src/unix/linux-syscalls.c:134: multiple definition of `uv__sendmmsg'
src/unix/.libs/libuv_la-linux-syscalls.o:/root/libuv-1.35.0/src/unix/linux-syscalls.c:134: first defined here
src/unix/.libs/libuv_la-linux-syscalls.o: In function `uv__statx':
/root/libuv-1.35.0/src/unix/linux-syscalls.c:187: multiple definition of `uv__statx'
src/unix/.libs/libuv_la-linux-syscalls.o:/root/libuv-1.35.0/src/unix/linux-syscalls.c:187: first defined here
src/unix/.libs/libuv_la-procfs-exepath.o: In function `uv_exepath':
/root/libuv-1.35.0/src/unix/procfs-exepath.c:28: multiple definition of `uv_exepath'
src/unix/.libs/libuv_la-procfs-exepath.o:/root/libuv-1.35.0/src/unix/procfs-exepath.c:28: first defined here
src/unix/.libs/libuv_la-random-getrandom.o: In function `uv__random_getrandom':
/root/libuv-1.35.0/src/unix/random-getrandom.c:56: multiple definition of `uv__random_getrandom'
src/unix/.libs/libuv_la-random-getrandom.o:/root/libuv-1.35.0/src/unix/random-getrandom.c:56: first defined here
src/unix/.libs/libuv_la-random-sysctl-linux.o: In function `uv__random_sysctl':
/root/libuv-1.35.0/src/unix/random-sysctl-linux.c:43: multiple definition of `uv__random_sysctl'
src/unix/.libs/libuv_la-random-sysctl-linux.o:/root/libuv-1.35.0/src/unix/random-sysctl-linux.c:43: first defined here
src/unix/.libs/libuv_la-sysinfo-loadavg.o: In function `uv_loadavg':
/root/libuv-1.35.0/src/unix/sysinfo-loadavg.c:28: multiple definition of `uv_loadavg'
src/unix/.libs/libuv_la-sysinfo-loadavg.o:/root/libuv-1.35.0/src/unix/sysinfo-loadavg.c:28: first defined here
clang70: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libuv.la] Error 1
```

**Comment by bnoordhuis** [comment]
Not sure what's up with that, it doesn't look like the same file is linked twice.

Android is not a supported platform so I'm going to close this but if you figure out the cause, please send a pull request.

**Comment by estasig** [comment]
https://github.com/libuv/libuv/commit/f9618443920fd0cbd3ab11c9d37c1f24a7aa1067

**Comment by kroggen** [comment]
indeed, it worked with version 1.33, prior to that commit.

**Comment by kroggen** [comment]
@estasig Thank you for your contribution!

You are right, I undid the f961844 commit from 1.40 and it worked without any problem.

Maintainers, keep in mind that when building for Android the system enables both `ANDROID` and `LINUX`, so the files are being included twice

**Comment by santigimeno** [comment]
@kroggen if reverting it fixes the issue. Could you open a PR with the revert?

**Comment by kroggen** [comment]
@santigimeno

done
