### PR TITLE
win: fix incompatible types warning

### PR DESCRIPTION
**Pull request by twose**
Warnings are treated as errors on our CI build, so we got some build errors.

Introduced by #3350
```
libuv\src\win\udp.c(1090,40): warning C4133: 'function': incompatible types - from 'sockaddr_storage *' to 'const sockaddr *'
```

### CODE REVIEW

**Comment by twose** [comment]
BTW, does libuv has debug builds on Github actions?
We met a stranger error which never occurred before:
https://github.com/libcat/libcat/runs/5759532749?check_suite_focus=true#step:7:297

```
Assertion failed: hrtime_frequency_ != 0, file D:\a\libcat\libcat\deps\libuv\src\win\util.c, line 500
```

image
